### PR TITLE
Fix bug in logger when log_to_console is set to false

### LINKED ISSUE #187: [BUG] Parameter changes are sent to stdout even though CUOPT_LOG_TO_CONSOLE is false
We call CUOPT_LOG_INFO when changing parameter settings inside solver settings. We should check the value of LOG_TO_CONSOLE before doing this. Or ensure that the logger is correctly setup.

### PR DESCRIPTION
**Pull request by rg20**
## Description

Prior to this PR,  some logging info relating to solver parameters was shown in stdout.  This is because we initialize the logger to stdout and we do not have apriori information whether the corresponding parameter would be set or not. In this PR, I am using the callback logger along with a log buffer to store all the logging info until the appropriate parameters and the loggers are initialized. 

## Issue

Closes #187 

## Checklist

- [ ] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/cuopt/blob/HEAD/CONTRIBUTING.md).
- Testing
   - [ ] New or existing tests cover these changes
   - [ ] Added tests
   - [ ] Created an issue to follow-up
   - [ ] NA
- Documentation
   - [ ] The documentation is up to date with these changes
   - [ ] Added new documentation
   - [ ] NA

## Summary by CodeRabbit

* **New Features**
  * Added log buffering to capture early messages and replay them when logging initializes.

* **Refactor**
  * Unified and simplified logging API with a scoped initializer for consistent startup/shutdown.

* **Chores**
  * Switched the codebase to the revised logging module across components.

* **Bug Fixes / Diagnostics**
  * Ensured logging is available on error paths and added extra CLI error handling to surface failures.

* **Tests**
  * Enhanced CLI test output with additional diagnostic printing.

### CODE REVIEW

**Review by aliceb-nv — APPROVED** [review]

File: cpp/src/utilities/logger.cpp [hunk 1]
```diff
@@ -15,13 +15,54 @@
...
 
-#include <rapids_logger/logger.hpp>
+// Buffer to store log messages
+class log_buffer {
+ public:
+  log_buffer()  = default;
+  ~log_buffer() = default;
 
-namespace cuopt {
+  void add(const char* msg)
```
Comment (akifcorduk) [inline cpp/src/utilities/logger.cpp]: Instead of `add`, would `log` sound better?

File: cpp/src/utilities/logger.cpp [hunk 2]
```diff
@@ -15,13 +15,54 @@
...
+{
+  static log_buffer buffer;
+  return buffer;
+}
+
+// Callback function for the buffer sink
+static void buffer_log_callback(int lvl, const char* msg)
+{
+  // FIXME:: check for levels?
+  global_log_buffer().add(msg);
```
Comment (akifcorduk) [inline cpp/src/utilities/logger.cpp]: I think levels might be important here, as you noticed.

**Review by akifcorduk — APPROVED** [review]

File: cpp/cuopt_cli.cpp [hunk 3]
```diff
@@ -131,23 +150,36 @@ int run_single_file(const std::string& file_path,
...
+      auto& lp_settings = settings.get_pdlp_settings();
+      auto solution     = cuopt::linear_programming::solve_lp(op_problem, lp_settings);
+    } else {
+      auto& mip_settings = settings.get_mip_settings();
+      auto solution      = cuopt::linear_programming::solve_mip(op_problem, mip_settings);
     }
   } catch (const std::exception& e) {
     CUOPT_LOG_ERROR("Error: %s", e.what());
     return -1;
   }
```
[the remark this answers is not in the document]
Comment (rg20) [reply cpp/cuopt_cli.cpp:177]: the solve function takes care of printing

**Review by tmckayus — APPROVED** [review]
