### PR TITLE
Merge update version and fix version format bugs

### LINKED ISSUE #262: [BUG] Update version script is not covering all the version format
**Describe the bug**
- [ ] Fix issue with alpha version tag, while releasing it is not removing alpha tags
- [ ] Doc versioning version1.json should get updated only once and shouldn't update again, also fix the issue with broken format.

### PR DESCRIPTION
**Pull request by rgsl888prabhu**
## Description
Merge update version which was earlier split was cuOpt and Rapids into one since we are in sync with versions now. 
And also fix failure in version updates and bugs around it.

## Issue
closes #262 

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/cuopt/blob/HEAD/CONTRIBUTING.md).
- Testing
   - [ ] New or existing tests cover these changes
   - [ ] Added tests
   - [ ] Created an issue to follow-up
   - [x] NA
- Documentation
   - [ ] The documentation is up to date with these changes
   - [ ] Added new documentation
   - [x] NA

### CODE REVIEW

**Review by tmckayus — APPROVED** [review]

**Comment by rgsl888prabhu** [comment]
@jameslamb may I get your review on this

File: ci/release/update-version.sh [hunk 1]
```diff
@@ -123,6 +123,49 @@ DEPENDENCIES=(
...
+done
+
+# RAPIDS-specific updates
+# RTD update for RAPIDS dependencies
+rapids_dependencies='cudf cudf-cu12 cuvs cuvs-cu12 libcudf librmm librmm-cu12 rmm rmm-cu12 librmm libraft-headers pylibraft pylibraft-cu12 raft-dask raft-dask-cu12 rapids-dask-dependency'
+for FILE in conda/environments/*.yaml dependencies.yaml; do
+    for dependency in ${rapids_dependencies}; do
+        sed_runner "s/\(${dependency}==\)[0-9]\+\.[0-9]\+/\1${NEXT_SHORT_TAG_PEP440}/" "${FILE}"
+    done
+done
```
Comment (jameslamb) [inline ci/release/update-version.sh]: This seems to be somewhat duplicating work that's done a few lines further down, like this:

```text
# Fixing RAPIDS dependencies and pyproject.toml
RAPIDS_DEPENDENCIES=(
  cudf
  cuvs
  librmm
  rmm
  pylibraft
  raft-dask
  rapids-dask-dependency
)

for DEP in "${RAPIDS_DEPENDENCIES[@]}"; do
  for FILE in dependencies.yaml conda/environments/*.yaml; do
    sed_runner "s/\(${DEP}==\)[0-9]\+\.[0-9]\+/\1${NEXT_SHORT_TAG_PEP440}/" "${FILE}"
  done
  for FILE in python/*/pyproject.toml; do
    sed_runner "s/\(${DEP}==\)[0-9]\+\.[0-9]\+/\1${NEXT_SHORT_TAG_PEP440}/" "${FILE}"
  done
done
```

Can you please consolidate them into just 1? And I think the later form, using a bash array, is preferable to this one using a long string.

File: ci/release/update-version.sh [hunk 2]
```diff
@@ -60,37 +65,36 @@ sed_runner 's/'"\"client_version\": \"[0-9][0-9].[0-9][0-9]\""'/'"\"client_versi
...
 # Update quick-start docs for pip
-sed_runner "s/\(cuopt-cu12==\)[0-9]\+\.[0-9]\+\.\\*/\1${PY_NEXT_SHORT_TAG}.\*/g" docs/cuopt/source/cuopt-python/quick-start.rst
-sed_runner "s/\(libcuopt-cu12==\)[0-9]\+\.[0-9]\+\.\\*/\1${PY_NEXT_SHORT_TAG}.\*/g" docs/cuopt/source/cuopt-c/quick-start.rst
-sed_runner "s/\(cuopt-server-cu12==\)[0-9]\+\.[0-9]\+\.\\*/\1${PY_NEXT_SHORT_TAG}.\*/g" docs/cuopt/source/cuopt-server/quick-start.rst
-sed_runner "s/\(cuopt-sh-client==\)[0-9]\+\.[0-9]\+\.\\*/\1${PY_NEXT_SHORT_TAG}.\*/g" docs/cuopt/source/cuopt-server/quick-start.rst
+sed_runner "s/\(cuopt-cu12==\)[0-9]\+\.[0-9]\+\.\\*/\1${NEXT_SHORT_TAG_PEP440}.\*/g" docs/cuopt/source/cuopt-python/quick-start.rst
+sed_runner "s/\(libcuopt-cu12==\)[0-9]\+\.[0-9]\+\.\\*/\1${NEXT_SHORT_TAG_PEP440}.\*/g" docs/cuopt/source/cuopt-c/quick-start.rst
+sed_runner "s/\(cuopt-server-cu12==\)[0-9]\+\.[0-9]\+\.\\*/\1${NEXT_SHORT_TAG_PEP440}.\*/g" docs/cuopt/source/cuopt-server/quick-start.rst
+sed_runner "s/\(cuopt-sh-client==\)[0-9]\+\.[0-9]\+\.\\*/\1${NEXT_SHORT_TAG_PEP440}.\*/g" docs/cuopt/source/cuopt-server/quick-start.rst
```
Comment (jameslamb) [inline ci/release/update-version.sh]: This is a lot of very-similar-looking changes to the same 2 files.

Would you please consider consolidating them and looping over a list of library names? Similar to this:

https://github.com/NVIDIA/cuopt/blob/0845a21e0a867babdce73325d1bcf748a32ca9d4/ci/release/update-version-rapids.sh#L70-L87

File: ci/release/update-version.sh (hunk 1 above)
Comment (jameslamb) [reply ci/release/update-version.sh]: Also now that these files are being combined, I don't think you need a separate list of "RAPIDS dependencies" vs. "cuopt dependencies".

So the update around line 43 that looks like this:

```shell
dependencies='libcuopt libcuopt-cu12 cuopt cuopt-cu12 cuopt-mps-parser cuopt-server cuopt-server-cu12 cuopt-sh-client'
for FILE in conda/environments/*.yaml dependencies.yaml; do
```

Should be consolidated here as well.

**Review by jameslamb — CHANGES_REQUESTED** [review]
Now that `cuopt` and RAPIDS will have aligned versions, there is a lot of opportunity for consolidating things in this new `update-version.sh` script. I left some specific examples I saw where things should be grouped into a smaller set of updates.

That'll make it run a little faster, reduce the risk of inconsistencies, and reduce the effort to maintain this.

Please also test this. Something like this:

```shell
./ci/release/update-version.sh '25.12.00'

# does the diff look like what you'd expect?
git diff

# did it catch everything?
git grep -E '24\.|25\.'
```

**Comment by rgsl888prabhu** [comment]
wanted to keep them separate in case if we need to be out of sync in future, but I think it can be done quite easily, will update PR as per your review

File: ci/release/update-version.sh [hunk 3]
```diff
@@ -37,60 +38,83 @@ function sed_runner() {
...
+  pylibraft
+  pylibraft-cu12
+  raft-dask
+  raft-dask-cu12
+  rapids-dask-dependency
+)
+
+for DEP in "${DEPENDENCIES[@]}"; do
+  for FILE in dependencies.yaml conda/environments/*.yaml python/*/pyproject.toml; do
+    sed_runner "s/\(${DEP}==\)[0-9]\+\.[0-9]\+/\1${NEXT_SHORT_TAG_PEP440}/" "${FILE}"
```
Comment (jameslamb) [inline ci/release/update-version.sh:61]:
```suggestion
    sed_runner "/-.* ${DEP}\(-cu[[:digit:]]\{2\}\)\{0,1\}\(\[.*\]\)\{0,1\}==/ s/==.*/==${NEXT_SHORT_TAG_PEP440}.*,>=0.0.0a0/g" "${FILE}"
```

Let's please use this pattern used throughout the rest of RAPIDS ([cudf example](https://github.com/rapidsai/cudf/blob/4a309b436685c605404fd82983673c1e94b7cd8c/ci/release/update-version.sh#L66)) which has the following nice properties:

* handles `-cu12` suffixes with an optional group, so no need to hard-code a bunch of `-cu12` entries in `DEPENDENCIES` (which would soon also need `-cu13` entries!)
* adds alpha specs to dependencies, so nightlies can be considered

File: ci/release/update-version.sh [hunk 4]
```diff
@@ -37,60 +38,83 @@ function sed_runner() {
...
+  librmm-cu12
+  libraft-headers
+  rmm
+  rmm-cu12
+  pylibraft
+  pylibraft-cu12
+  raft-dask
+  raft-dask-cu12
+  rapids-dask-dependency
+)
```
Comment (jameslamb) [inline ci/release/update-version.sh]:
```suggestion
DEPENDENCIES=(
  cudf
  cuvs
  cuopt
  cuopt-mps-parser
  cuopt-server
  cuopt-sh-client
  libcuopt
  libraft-headers
  librmm
  pylibraft
  raft-dask
  rapids-dask-dependency
  rmm
)
```

Let's please alphabetize this (so it's easier to read at a glance) and remove `-cu12` entries (see next comment).

File: ci/release/update-version.sh [hunk 5]
```diff
@@ -37,60 +38,83 @@ function sed_runner() {
...
+  done
+  for FILE in docs/cuopt/source/*/quick-start.rst README.md; do
+    sed_runner "s/\(${DEP}==\)[0-9]\+\.[0-9]\+\.\\*/\1${NEXT_SHORT_TAG_PEP440}.\*/g" "${FILE}"
+  done
+  for FILE in docs/cuopt/source/*/quick-start.rst README.md; do
+    sed_runner "s/\(${DEP}=\)[0-9]\+\.[0-9]\+\(\.[0-9]\+\)\?[^ ]*/\1${NEXT_SHORT_TAG}.*/g" "${FILE}"
+  done
+  for FILE in docs/cuopt/source/*/quick-start.rst README.md; do
+    sed_runner "s/\(${DEP}:\)[0-9]\{2\}\.[0-9]\{1,2\}\.[0-9]\+\(-cuda[0-9]\+\.[0-9]\+-\)\(py[0-9]\+\)/\1${DOCKER_TAG}\2\3/g" docs/cuopt/source/cuopt-python/quick-start.rst
+  done
```
Comment (jameslamb) [inline ci/release/update-version.sh]:
```suggestion
  for FILE in docs/cuopt/source/*/quick-start.rst README.md; do
    sed_runner "s/\(${DEP}==\)[0-9]\+\.[0-9]\+\.\\*/\1${NEXT_SHORT_TAG_PEP440}.\*/g" "${FILE}"
    sed_runner "s/\(${DEP}=\)[0-9]\+\.[0-9]\+\(\.[0-9]\+\)\?[^ ]*/\1${NEXT_SHORT_TAG}.*/g" "${FILE}"
  done
  sed_runner "s/\(${DEP}:\)[0-9]\{2\}\.[0-9]\{1,2\}\.[0-9]\+\(-cuda[0-9]\+\.[0-9]\+-\)\(py[0-9]\+\)/\1${DOCKER_TAG}\2\3/g" docs/cuopt/source/cuopt-python/quick-start.rst
```

This is currently looping over the same set of files 3 times.

Let's consolidate 2 of those calls so we only loop over the files once, and run that additional line that only applies to  `docs/cuopt/source/cuopt-python/quick-start.rst` outside of the `for FILE` loop, since it only applies to one file.

File: ci/release/update-version.sh [hunk 6]
```diff
@@ -100,29 +124,20 @@ sed_runner "/^set(cuopt_version/ s/[0-9][0-9].[0-9][0-9].[0-9][0-9]/${NEXT_FULL_
...
+  # CI image tags of the form {rapids_version}-{something}
+  sed_runner "s/:[0-9]*\\.[0-9]*-/:${NEXT_SHORT_TAG}-/g" "${FILE}"
 done
+
+# CI for RAPIDS
+sed_runner 's/'"DEPENDENT_PACKAGE_VERSION=\"[0-9][0-9].[0-9][0-9]\""'/'"DEPENDENT_PACKAGE_VERSION=\"${NEXT_SHORT_TAG}\""'/g' ci/build_cpp.sh
+sed_runner 's/'"DEPENDENT_PACKAGE_VERSION=\"[0-9][0-9].[0-9][0-9]\""'/'"DEPENDENT_PACKAGE_VERSION=\"${NEXT_SHORT_TAG}\""'/g' ci/build_python.sh
+
+# PYTHON for RAPIDS
+sed_runner "/DOWNLOAD.*rapids-cmake/ s/branch-[0-9][0-9].[0-9][0-9]/branch-${NEXT_SHORT_TAG}/g" python/cuopt/CMakeLists.txt
```
Comment (jameslamb) [inline ci/release/update-version.sh]:
```suggestion
sed_runner "/DOWNLOAD.*rapids-cmake/ s/branch-[0-9][0-9].[0-9][0-9]/branch-${NEXT_SHORT_TAG}/g" python/cuopt/CMakeLists.txt

```

Please add a newline here. I think you should just let `pre-commit` handle this.

Remove `files:` from this:

https://github.com/NVIDIA/cuopt/blob/0845a21e0a867babdce73325d1bcf748a32ca9d4/.pre-commit-config.yaml#L20-L22

And only use the `exclude:` pattern to handle excluding files you don't want the check to cover.

That way, by default the hook will cover all files in the repo, so you don't need to remember to keep adding file extensions (in this case, `.sh`).

File: ci/release/update-version.sh [hunk 7]
```diff
@@ -100,29 +124,20 @@ sed_runner "/^set(cuopt_version/ s/[0-9][0-9].[0-9][0-9].[0-9][0-9]/${NEXT_FULL_
...
+for FILE in .github/workflows/*.yaml; do
+  sed_runner "/shared-workflows/ s/@.*/@branch-${NEXT_SHORT_TAG}/g" "${FILE}"
+  # CI image tags of the form {rapids_version}-{something}
+  sed_runner "s/:[0-9]*\\.[0-9]*-/:${NEXT_SHORT_TAG}-/g" "${FILE}"
 done
+
+# CI for RAPIDS
+sed_runner 's/'"DEPENDENT_PACKAGE_VERSION=\"[0-9][0-9].[0-9][0-9]\""'/'"DEPENDENT_PACKAGE_VERSION=\"${NEXT_SHORT_TAG}\""'/g' ci/build_cpp.sh
+sed_runner 's/'"DEPENDENT_PACKAGE_VERSION=\"[0-9][0-9].[0-9][0-9]\""'/'"DEPENDENT_PACKAGE_VERSION=\"${NEXT_SHORT_TAG}\""'/g' ci/build_python.sh
+
```
Comment (jameslamb) [inline ci/release/update-version.sh]:
```suggestion
```

You already have `RAPIDS_VERSION` in a file in the repo. Instead of doing this:

https://github.com/NVIDIA/cuopt/blob/0845a21e0a867babdce73325d1bcf748a32ca9d4/ci/build_cpp.sh#L35

How about doing this in those scripts?

```shell
DEPENDENT_PACKAGE_VERSION=$(cat ./RAPIDS_VERSION)
export DEPENDENT_PACKAGE_VERSION
```

That way, you don't need to update this in shell scripts... just drive everything through those `VERSION` and `RAPIDS_VERSION` files.

That'd mean fewer updates, less risk of inconsistencies, and an easier-to-understand configuration flow.

File: ci/release/update-version.sh [hunk 8]
```diff
@@ -37,60 +38,83 @@ function sed_runner() {
 
 # Centralized version file update
 echo "${NEXT_FULL_TAG}" > VERSION
+echo "${NEXT_FULL_TAG}" > RAPIDS_VERSION
```
Comment (jameslamb) [inline ci/release/update-version.sh]:
```suggestion
echo "${NEXT_FULL_TAG}" > ./VERSION
echo "${NEXT_FULL_TAG}" > ./RAPIDS_VERSION
```

Very very very minor comment, ignore if you want... I find it useful to add a leading `./` to stuff like this, to make it clear that we're piping to a file and not a shell variable.

**Review by jameslamb — CHANGES_REQUESTED** [review]
Thanks for the updates. I've left some more suggestions.

File: ci/release/update-version.sh (hunk 7 above)
Comment (ramakrishnap-nv) [reply ci/release/update-version.sh]: RAPIDS_VERSION has 25.10.00 instead of 25.10, but let me try if it fixes it.

File: ci/release/update-version.sh (hunk 6 above)
Comment (ramakrishnap-nv) [reply ci/release/update-version.sh]: I will make this change in a new PR since it will touch too many files. But make the suggested change manually for now.

Comment (ramakrishnap-nv) [reply ci/release/update-version.sh]: Created this PR https://github.com/NVIDIA/cuopt/pull/306

File: ci/release/update-version.sh (hunk 7 above)
Comment (jameslamb) [reply ci/release/update-version.sh]: Ah ok. Well still, the more important part of this recommendation is using the file, to limit how many places the same version is hard-coded. You could modify that statement to only pull out the major and minor version.

Comment (ramakrishnap-nv) [reply ci/release/update-version.sh]: Seems like it works as it is, so it should be good.

**Comment by rgsl888prabhu** [comment]
@jameslamb May I get your review on this ?

File: ci/release/update-version.sh [hunk 9]
```diff
@@ -0,0 +1,126 @@
...
+# CMakeLists update
+sed_runner 's/'"VERSION [0-9][0-9].[0-9][0-9].[0-9][0-9]"'/'"VERSION ${NEXT_FULL_TAG}"'/g' cpp/CMakeLists.txt
+sed_runner 's/'"VERSION [0-9][0-9].[0-9][0-9].[0-9][0-9]"'/'"VERSION ${NEXT_FULL_TAG}"'/g' cpp/libmps_parser/CMakeLists.txt
+sed_runner 's/'"DEPENDENT_LIB_MAJOR_VERSION \"[0-9][0-9]\""'/'"DEPENDENT_LIB_MAJOR_VERSION \"${NEXT_MAJOR}\""'/g' cpp/CMakeLists.txt
+sed_runner 's/'"DEPENDENT_LIB_MINOR_VERSION \"[0-9][0-9]\""'/'"DEPENDENT_LIB_MINOR_VERSION \"${NEXT_MINOR}\""'/g' cpp/CMakeLists.txt
+
+# Server version update
+sed_runner 's/'"\"version\": \"[0-9][0-9].[0-9][0-9]\""'/'"\"version\": \"${NEXT_SHORT_TAG}\""'/g' python/cuopt_server/cuopt_server/utils/data_definition.py
+sed_runner 's/'"\"client_version\": \"[0-9][0-9].[0-9][0-9]\""'/'"\"client_version\": \"${NEXT_SHORT_TAG}\""'/g' python/cuopt_server/cuopt_server/utils/routing/data_definition.py
+sed_runner 's/'"\"client_version\": \"[0-9][0-9].[0-9][0-9]\""'/'"\"client_version\": \"${NEXT_SHORT_TAG}\""'/g' python/cuopt_server/cuopt_server/utils/linear_programming/data_definition.py
```
Comment (jameslamb) [inline ci/release/update-version.sh:82]: I think it would be good to calculate this programmatically, in Python code instead.

e.g.

https://github.com/NVIDIA/cuopt/blob/b567ed4c15daf5650cda2ea118cc13e12d5db822/python/cuopt_server/cuopt_server/utils/routing/data_definition.py#L1029

Should rely on this constant:

https://github.com/NVIDIA/cuopt/blob/b567ed4c15daf5650cda2ea118cc13e12d5db822/python/cuopt_server/cuopt_server/_version.py#L18

Same advice goes for all 3 of these lines.

File: ci/release/update-version.sh [hunk 10]
```diff
@@ -0,0 +1,126 @@
...
+
+# Doc update
+sed_runner 's/'"version = \"[0-9][0-9].[0-9][0-9]\""'/'"version = \"${NEXT_SHORT_TAG}\""'/g' docs/cuopt/source/conf.py
```
Comment (jameslamb) [inline ci/release/update-version.sh:85]: This should use `cuopt.__version__` instead.

Example of how `cudf` does this: https://github.com/rapidsai/cudf/blob/21b69cf8c31c42bf981c5c8987b4d0d6ff36b3d5/docs/cudf/source/conf.py#L189-L195

File: ci/release/update-version.sh [hunk 11]
```diff
@@ -0,0 +1,126 @@
...
+sed_runner 's/'"PROJECT_NUMBER         = [0-9][0-9].[0-9][0-9]"'/'"PROJECT_NUMBER         = ${NEXT_SHORT_TAG}"'/g' cpp/doxygen/Doxyfile
```
Comment (jameslamb) [inline ci/release/update-version.sh:86]: `Doxyfile`s can be templated and filled in at runtime with environment variables. This project should consider doing that.

Example from `raft`:

https://github.com/rapidsai/raft/blob/e6efdd1143c988a366619965bcdd891a4474ea7e/cpp/doxygen/Doxyfile#L41

https://github.com/rapidsai/raft/blob/e6efdd1143c988a366619965bcdd891a4474ea7e/ci/build_docs.sh#L13

File: ci/release/update-version.sh [hunk 12]
```diff
@@ -0,0 +1,126 @@
...
+if ! grep -q "\"version\": \"${NEXT_FULL_TAG}\"" "${VERSIONS_FILE}"; then
+  # Remove preferred and latest flags, but keep the version entry and URL
+  sed_runner '/"name": "latest",/d' "${VERSIONS_FILE}"
+  sed_runner '/"preferred": true,\?/d' "${VERSIONS_FILE}"
+  # Remove trailing comma after "url": ... in all version entries
+  sed_runner 's/\("url": "[^"]*"\),/\1/' "${VERSIONS_FILE}"
+  # Add new version entry with both preferred and latest flags
+  NEW_VERSION_ENTRY='    {\n      "version": "'${NEXT_FULL_TAG}'",\n      "url": "../'${NEXT_FULL_TAG}'/",\n      "name": "latest",\n      "preferred": true\n    },'
+  sed_runner "/\[/a\\${NEW_VERSION_ENTRY}" "${VERSIONS_FILE}"
+fi
```
Comment (jameslamb) [inline ci/release/update-version.sh:104]: I think you might find this easier to maintain if it was in Python.

I recommend looking into what I just did over in the `docs` repo:

* https://github.com/rapidsai/docs/pull/669
* https://github.com/rapidsai/docs/pull/670

I think you should have a small Python script that populates `versions1.json`, and a `pre-commit` hook that runs it.

And that script should read from `./VERSION` at the root of the repo.

That'd simplify `update-version.sh`, and make it easier to keep that file up to date.

File: ci/release/update-version.sh [hunk 13]
```diff
@@ -0,0 +1,126 @@
...
+
+# RTD update
+sed_runner "/^set(cuopt_version/ s/[0-9][0-9].[0-9][0-9].[0-9][0-9]/${NEXT_FULL_TAG}/g" python/cuopt/CMakeLists.txt
+sed_runner "/^set(cuopt_version/ s/[0-9][0-9].[0-9][0-9].[0-9][0-9]/${NEXT_FULL_TAG}/g" python/cuopt/cuopt/linear_programming/CMakeLists.txt
+sed_runner "/^set(cuopt_version/ s/[0-9][0-9].[0-9][0-9].[0-9][0-9]/${NEXT_FULL_TAG}/g" python/libcuopt/CMakeLists.txt
```
Comment (jameslamb) [inline ci/release/update-version.sh:109]: It should be possible to derive all of these in CMake, at configure time, from other variables.

Re-using all of these variables:

https://github.com/NVIDIA/cuopt/blob/b567ed4c15daf5650cda2ea118cc13e12d5db822/cmake/rapids_config.cmake#L15-L21

File: ci/release/update-version.sh [hunk 14]
```diff
@@ -0,0 +1,126 @@
...
+sed_runner 's/\(version: \)[0-9][0-9]\.[0-9]\+\.[0-9]\+/\1'${DOCKER_TAG}'/g' helmchart/cuopt-server/Chart.yaml
+
+for FILE in .github/workflows/*.yaml; do
+  sed_runner "/shared-workflows/ s/@.*/@branch-${NEXT_SHORT_TAG}/g" "${FILE}"
+  # CI image tags of the form {rapids_version}-{something}
+  sed_runner "s/:[0-9]*\\.[0-9]*-/:${NEXT_SHORT_TAG}-/g" "${FILE}"
+done
+
+# PYTHON for RAPIDS
+sed_runner "/DOWNLOAD.*rapids-cmake/ s/branch-[0-9][0-9].[0-9][0-9]/branch-${NEXT_SHORT_TAG}/g" python/cuopt/CMakeLists.txt
```
Comment (jameslamb) [inline ci/release/update-version.sh:126]: This should be grouped with the other `CMakeLists.txt` updates further up.

And similar to my comment on those, I think it'd be better to move this logic into CMake code itself.

**Review by jameslamb — APPROVED** [review]
Approving this so you can keep moving forward. But if you haven't already, please do test it one more time, in the way I described in https://github.com/NVIDIA/cuopt/pull/286#pullrequestreview-3117686535

I also think you should write up a follow-up issue about consolidating the references to versions in this project. I left a couple of suggestions, but overall there are very very many hard-coded `25.10` around the source code that all need to be kept in sync.

For inspiration, you could look at some of the PRs @KyleFromNVIDIA put up around RAPIDS implementing similar things to what I've suggested here: https://github.com/rapidsai/build-planning/issues/15
