### PR TITLE
Parallel Branch-and-Bound

### LINKED ISSUE #320: [BUG] cuOpt MIP solver log does not report final solution
cuOpt MIP solver log (in log file or on screen) does not report the final feasible solution upon time limit running out when root node solution process (Dual Simplex Phase 2) is still unfinished, but the primal heuristics has found a feasible solution.

This issue was encountered with a private file shared by a user, but I suspect it can be replicated when
- the MIP problem is sufficiently large or difficult and root node solve takes considerable time
- the solver is provided with a short time budget that does not allow root node solve to finish, but primal heuristics can still generate a feasible solution.

Expectation:
Log file or screen log showing the final feasible solution found by the Primal Heuristics.

This was observed when running a MIP MPS file on H100 80GB HBM3 with:
- 101983 constraints 34467 variables (34296 integers) and 303046 nonzeros

cuOpt was built from source and cuopt_cli was executed as follows:
cuopt_cli --presolve t --mip-heuristics-only f --log-file <file_name> --time-limit 900 <mps_file_name>

### LINKED ISSUE #417: [BUG] cuopt incorrectly report optimal integer solution when the objective offset is very large
Branch-and-Bound incorrectly state that an optimal integer solution has been found within the relative gap tolerance when a large offset is applied to the objective during the presolve. 

This can be trigger by running the PR #405 over the `supportcase42` instance from MIPLIB. At the end of the procedure, B&B report that it found an optimal solution with `user_objective = 9`, however, the true optimal objective is `7.75863072227` according to the [MIPLIB site](https://miplib.zib.de/instance_details_supportcase42.html). In this case, the solver actually see the bounds and relative gap as  `relative gap = 0.000062, upper_bound = 26784.000000, lower_bound = 26782.343661`. Below are the full log.

```
❯ cuopt-ref/cpp/build/solve_MIP --path datasets/miplib2017/supportcase42.mps.bz2 --time-limit 100
running file supportcase42.mps.bz2 on gpu : 0
cuOpt version: 25.10.0, git hash: ef90a38, host arch: x86_64, device archs: 90a-real
CPU: Intel(R) Xeon(R) Silver 4314 CPU @ 2.40GHz, threads (physical/logical): 16/32, RAM: 152.80 GiB
CUDA 13.0, device: NVIDIA H100 (ID 0), VRAM: 95.07 GiB
CUDA device UUID: ffffff9947ffffffb571-051b-6d68-fffff

Unpresolved problem:: 18439 constraints, 19466 variables, 435653 nonzeros
Presolve status:: reduced the problem
Presolve removed:: 282 constraints, 283 variables, 564 nonzeros
Presolved problem:: 18157 constraints, 19183 variables, 435089 nonzeros
Third party presolve time: 0.122674
Solving a problem with 18157 constraints 19183 variables (1026 integers) and 435089 nonzeros
Objective offset -26775.000000 scaling_factor 1.000000
Free variable found! Make sure the correct bounds are given.
Running presolve!
After trivial presolve #constraints 18157 #variables 20069 objective offset -26775.000000.
Using 4 CPU threads for B&B
Solving LP root relaxation
Scaling matrix. Maximum column norm 5.562658e+01
Dual Simplex Phase 1
Dual feasible solution found.
Dual Simplex Phase 2
 Iter     Objective           Num Inf.  Sum Inf.     Perturb  Time
    1 +0.0000000000000000e+00       2 3.33333333e+02 1.00e-07 0.07
Failed to remove perturbation of 1.85e-04.

Root relaxation solution found in 504 iterations and 0.37s
Root relaxation objective +7.34366096e+00

Strong branching using 4 threads and 174 fractional variables
CPUFJ added a solution to population, solution queue size 0 with objective 39.9999
CPUFJ added a solution to population, solution queue size 0 with objective 9.9999
CPUFJ added a solution to population, solution queue size 0 with objective 8.9999
New solution from primal heuristics. Objective +2.157089e+01. Time 0.58
Running FP alone!
CPUFJ added a solution to population, solution queue size 0 with objective 38.9999
CPUFJ added a solution to population, solution queue size 0 with objective 37.9999
CPUFJ added a solution to population, solution queue size 0 with objective 36.9998
CPUFJ added a solution to population, solution queue size 0 with objective 35.9999
CPUFJ added a solution to population, solution queue size 0 with objective 34.9999
CPUFJ added a solution to population, solution queue size 0 with objective 33.9999
CPUFJ added a solution to population, solution queue size 0 with objective 32.9999
CPUFJ added a solution to population, solution queue size 0 with objective 31.9999
CPUFJ added a solution to population, solution queue size 0 with objective 30.9999
CPUFJ added a solution to population, solution queue size 0 with objective 29.9999
CPUFJ added a solution to population, solution queue size 0 with objective 28.9999
CPUFJ added a solution to population, solution queue size 0 with objective 27.9999
CPUFJ added a solution to population, solution queue size 0 with objective 26.9999
| Explored | Unexplored | Objective   |    Bound    | Depth | Iter/Node |  Gap   |    Time 
        1        1       +2.157089e+01  +7.343661e+00      1   0.0e+00     66.0%      2.10
CPUFJ added a solution to population, solution queue size 0 with objective 25.9999
CPUFJ added a solution to population, solution queue size 0 with objective 24.9999
CPUFJ added a solution to population, solution queue size 0 with objective 24.238
CPUFJ added a solution to population, solution queue size 0 with objective 23.238
CPUFJ added a solution to population, solution queue size 0 with objective 22.238
CPUFJ added a solution to population, solution queue size 0 with objective 22.2379
       48       48       +2.157089e+01  +7.343661e+00     14   4.2e-01     66.0%      3.10
CPUFJ added a solution to population, solution queue size 0 with objective 22.2378
       97       97       +2.157089e+01  +7.343661e+00     22   2.1e-01     66.0%      4.10
      145      145       +2.157089e+01  +7.343661e+00     29   1.4e-01     66.0%      5.11
      194      194       +2.157089e+01  +7.343661e+00     35   1.0e-01     66.0%      6.13
      243      243       +2.157089e+01  +7.343661e+00     41   8.2e-02     66.0%      7.14
      292      292       +2.157089e+01  +7.343661e+00     47   6.8e-02     66.0%      8.15
      341      341       +2.157089e+01  +7.343661e+00     51   5.9e-02     66.0%      9.15
      388      388       +2.157089e+01  +7.343661e+00     58   5.2e-02     66.0%     10.15
      437      437       +2.157089e+01  +7.343661e+00     63   4.6e-02     66.0%     11.17
      486      486       +2.157089e+01  +7.343661e+00     67   4.1e-02     66.0%     12.18
      535      535       +2.157089e+01  +7.343661e+00     74   3.7e-02     66.0%     13.19
      584      584       +2.157089e+01  +7.343661e+00     79   3.4e-02     66.0%     14.20
      633      633       +2.157089e+01  +7.343661e+00     45   3.2e-02     66.0%     15.21
      682      682       +2.157089e+01  +7.343661e+00     89   2.9e-02     66.0%     16.23
      731      731       +2.157089e+01  +7.343661e+00     92   2.7e-02     66.0%     17.25
      779      779       +2.157089e+01  +7.343661e+00     87   2.6e-02     66.0%     18.26
      828      828       +2.157089e+01  +7.343661e+00    103   2.4e-02     66.0%     19.27
      878      878       +2.157089e+01  +7.343661e+00    108   2.3e-02     66.0%     20.29
      927      927       +2.157089e+01  +7.343661e+00    113   2.2e-02     66.0%     21.31
      976      976       +2.157089e+01  +7.343661e+00    118   2.0e-02     66.0%     22.32
     2000     2000       +2.157089e+01  +7.343661e+00    173   1.0e-02     66.0%     44.36
     3000     3000       +2.157089e+01  +7.343661e+00    257   6.7e-03     66.0%     65.45
     4000     4000       +2.157089e+01  +7.343661e+00    379   5.0e-03     66.0%     86.25
FP alone finished!
Killing CPU solver
Killing CPU solver
     4649     4649       +2.157089e+01  +7.343661e+00    391   4.3e-03     66.0%     99.80
Hit time limit. Stopping
H                        +1.000000e+01  +7.343661e+00                      26.6%     99.81
H                        +9.000000e+00  +7.343661e+00                      18.4%     99.81
Explored 4649 nodes in 99.81s.
Absolute Gap 1.422723e+01 Objective 9.0000000000000000e+00 Lower Bound 7.3436609543532541e+00
relative gap: 0.000062, upper_bound = 26784.000000, lower_bound = 26782.343661
Optimal solution found within relative MIP gap tolerance (1.0e-04)
Killing CPU solver
Killing CPU solver
Killing CPU solver
Killing CPU solver
Killing CPU solver
Killing CPU solver
Killing CPU solver
Killing CPU solver
Post-solve status:: succeeded
Solution objective: 9.000000 , relative_mip_gap 0.184038 solution_bound 7.343661 presolve_time 0.126977 total_solve_time 100.051471 max constraint violation 0.000000 max int violation 0.000000 max var bounds violation 0.000000 nodes 4649 simplex_iterations 20
first obj: 0.000000 last improvement of best feasible: 100.048658 last improvement after recombination: 0.000000
run_solver 100097
supportcase42.mps.bz2: solution found, obj: 9.000000

```

### PR DESCRIPTION
**Pull request by nguidotti**
## Description

This PR implement a parallel branch-and-bound procedure, which is split into two phases. In the first phase, the algorithm will greedily expand the search tree until a certain depth and then add the bottom nodes to a global heap. The parallel expansion is implemented using  `omp task`.

In the second phase, some threads will explore the tree using best first search with plunging, i.e., they take the first node from the global heap and then explore the entire branch that starts on this node. Any unexplored node are insert into the heap. The remaining threads will perform deep dives in order to find feasible solutions. The solver keep a small heap contains the most promising nodes to perform the dives, which is keep in sync with the global heap. 

This PR also
- Replace the `std::thread`-based parallelization in the strong branching with OpenMP in order to use dynamic scheduling. This ensures that all threads have similar amount of work and improve parallel performance.
- Fixed invalid memory access when trying to access the status of a fathomed node.   
- Replaced `std::mutex` with `omp atomic` whatever applicable. 
- Added dedicated classes  `dive_queue_t` and `search_tree_t` to store the diving heap and the search tree, respectively.

This is an extension of #305.
Closes #320.
Closes #417.

## Benchmark results (MIPLIB2017):

master branch (53d6e74)
```
Average Gap: 0.2174861712
```

This PR:
```
Average Gap: 0.1989485546
```

i.e., a `1.8%` improvement. In terms of the geomean of the gap ratio, this is equal to `1.62x`.

## Checklist

- [X] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/cuopt/blob/HEAD/CONTRIBUTING.md).
- Testing
   - [X] New or existing tests cover these changes
   - [ ] Added tests
   - [ ] Created an issue to follow-up
   - [ ] NA
- Documentation
   - [ ] The documentation is up to date with these changes
   - [ ] Added new documentation
   - [X] NA

### CODE REVIEW

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 1]
```diff
@@ -609,259 +597,399 @@ mip_status_t branch_and_bound_t<i_t, f_t>::solve_node_lp(
...
+    lower_bound = get_lower_bound();
+    upper_bound = get_upper_bound();
+    gap         = upper_bound - lower_bound;
+
+  } while (get_status() == mip_status_t::RUNNING && gap > settings_.absolute_mip_gap_tol &&
+           relative_gap(upper_bound, lower_bound) > settings_.relative_mip_gap_tol &&
+           (get_active_subtrees() > 0 || get_heap_size() > 0));
+
+  // Check if the solver exited naturally, or was due to a timeout or numerical error.
+  if (status_ == mip_status_t::RUNNING) {
```
Comment (aliceb-nv) [inline cpp/src/dual_simplex/branch_and_bound.cpp]: Should that be a `#pragma omp atomic read`?
It might be valuable to create a omp_atomic<T> (like std::atomic) type to encapsulate omp atomic operations and ensure a variable isn't simultaneously accessed by atomic and non-atomic operations

File: cpp/src/dual_simplex/branch_and_bound.hpp [hunk 2]
```diff
@@ -43,15 +40,54 @@ enum class mip_status_t {
...
+  std::vector<mip_node_t<i_t, f_t>> buffer;
+  std::mutex mutex;
+  static constexpr i_t max_size_ = 8192;
+
+ public:
+  dive_queue_t() { buffer.reserve(max_size_); }
+
+  void push(mip_node_t<i_t, f_t>&& node)
+  {
+    buffer.push_back(std::forward<mip_node_t<i_t, f_t>&&>(node));
```
Comment (aliceb-nv) [inline cpp/src/dual_simplex/branch_and_bound.hpp]: Shouldn't that just be std::move? std::forward is for universal references IIRC

File: cpp/src/dual_simplex/mip_node.hpp [hunk 3]
```diff
@@ -230,11 +242,102 @@ void remove_fathomed_nodes(std::vector<mip_node_t<i_t, f_t>*>& stack)
...
+template <typename i_t, typename f_t>
+class search_tree_t {
+ public:
+  search_tree_t(f_t root_lower_bound, const std::vector<variable_status_t>& basis, logger_t& log)
+    : root(root_lower_bound, basis), num_nodes(0), log(log)
+  {
+  }
+
+  search_tree_t(mip_node_t<i_t, f_t>&& node, logger_t& log)
+    : root(std::forward<mip_node_t<i_t, f_t>&&>(node)), num_nodes(0), log(log)
```
Comment (aliceb-nv) [inline cpp/src/dual_simplex/mip_node.hpp]: std::move?

File: cpp/src/dual_simplex/simplex_solver_settings.hpp [hunk 4]
```diff
@@ -59,9 +59,9 @@ struct simplex_solver_settings_t {
       refactor_frequency(100),
       iteration_log_frequency(1000),
       first_iteration_log(2),
-      num_threads(std::thread::hardware_concurrency() > 8
-                    ? (std::thread::hardware_concurrency() / 8)
-                    : std::thread::hardware_concurrency()),
+      num_threads(std::thread::hardware_concurrency() - 1),
+      num_bfs_threads(std::min(num_threads, 4)),
+      num_diving_threads(num_threads - num_bfs_threads),
```
Comment (aliceb-nv) [inline cpp/src/dual_simplex/simplex_solver_settings.hpp]: Should we guarantee one diving thread at least maybe? The following code might make this assumption (and diving even with thread contention might be better than none at all)

File: cpp/src/mip/diversity/recombiners/sub_mip.cuh [hunk 5]
```diff
@@ -112,6 +112,7 @@ class sub_mip_recombiner_t : public recombiner_t<i_t, f_t> {
       branch_and_bound_settings.absolute_mip_gap_tol = context.settings.tolerances.absolute_mip_gap;
       branch_and_bound_settings.relative_mip_gap_tol = context.settings.tolerances.relative_mip_gap;
       branch_and_bound_settings.integer_tol = context.settings.tolerances.integrality_tolerance;
+      branch_and_bound_settings.num_threads = 1;
```
Comment (aliceb-nv) [inline cpp/src/mip/diversity/recombiners/sub_mip.cuh]: Have we experimented with this parameter? Submip tends to yield good solutions, it might perform better with a few more threads allocated

File: cpp/src/dual_simplex/branch_and_bound.hpp [hunk 6]
```diff
@@ -43,15 +40,54 @@ enum class mip_status_t {
   TIME_LIMIT = 3,
   NODE_LIMIT = 4,
   NUMERICAL  = 5,
-  UNSET      = 6
+  UNSET      = 6,
+  RUNNING    = 7,
+  FINISHED   = 8
```
Comment (rg20) [inline cpp/src/dual_simplex/branch_and_bound.hpp]: does n't finish mean optimal/unbounded/infeasible ?

File: cpp/src/dual_simplex/mip_node.hpp [hunk 7]
```diff
@@ -201,6 +202,17 @@ class mip_node_t {
     }
   }
 
+  mip_node_t<i_t, f_t> detach_copy() const
```
Comment (rg20) [inline cpp/src/dual_simplex/mip_node.hpp:209]: Is n't this equivalent to copy constructor right?

File: cpp/src/mip/diversity/recombiners/sub_mip.cuh (hunk 5 above)
Comment (nguidotti) [reply cpp/src/mip/diversity/recombiners/sub_mip.cuh]: Not yet. It was set to `1` to avoid oversubscription of the threads. I can allocate a few more threads to submip and see how it behaves.

File: cpp/src/dual_simplex/mip_node.hpp [hunk 8]
```diff
@@ -230,11 +242,102 @@ void remove_fathomed_nodes(std::vector<mip_node_t<i_t, f_t>*>& stack)
 template <typename i_t, typename f_t>
 class node_compare_t {
  public:
-  bool operator()(mip_node_t<i_t, f_t>& a, mip_node_t<i_t, f_t>& b)
+  bool operator()(mip_node_t<i_t, f_t>& a, mip_node_t<i_t, f_t>& b) const
```
Comment (rg20) [inline cpp/src/dual_simplex/mip_node.hpp]:
```suggestion
  bool operator()(mip_node_t<i_t, f_t> const & a, mip_node_t<i_t, f_t> const & b) const
```

File: cpp/src/dual_simplex/mip_node.hpp [hunk 9]
```diff
@@ -230,11 +242,102 @@ void remove_fathomed_nodes(std::vector<mip_node_t<i_t, f_t>*>& stack)
...
   {
     return a.lower_bound >
            b.lower_bound;  // True if a comes before b, elements that come before are output last
   }
+
+  bool operator()(mip_node_t<i_t, f_t>* a, mip_node_t<i_t, f_t>* b) const
```
Comment (rg20) [inline cpp/src/dual_simplex/mip_node.hpp]:
```suggestion
  bool operator()(mip_node_t<i_t, f_t> const * a, mip_node_t<i_t, f_t> const* b) const
```

File: cpp/src/dual_simplex/mip_node.hpp [hunk 10]
```diff
@@ -230,11 +242,102 @@ void remove_fathomed_nodes(std::vector<mip_node_t<i_t, f_t>*>& stack)
...
+
+  void branch(mip_node_t<i_t, f_t>* parent_node,
+              i_t branch_var,
+              f_t branch_var_val,
+              const std::vector<variable_status_t>& parent_vstatus,
+              const lp_problem_t<i_t, f_t>& original_lp)
+  {
+    i_t id;
+
+#pragma omp atomic capture
```
Comment (rg20) [inline cpp/src/dual_simplex/mip_node.hpp]: We are using a mix of std::thread and openmp.   Can we move to using only `std::thread` ?

File: cpp/src/dual_simplex/simplex_solver_settings.hpp (hunk 4 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/simplex_solver_settings.hpp]: True. Also, if `num_threads < 4`, there will be have no diving threads. Instead, we can set something like this:
```cpp
num_bfs_threads = std::min(1, num_threads / 4)
num_diving_threads = std::min(1, num_threads - num_bfs_threads)
```

File: cpp/src/dual_simplex/mip_node.hpp [hunk 11]
```diff
@@ -230,11 +242,102 @@ void remove_fathomed_nodes(std::vector<mip_node_t<i_t, f_t>*>& stack)
...
+      original_lp, parent_node, ++id, branch_var, 1, branch_var_val, parent_vstatus);
+
+    graphviz_edge(parent_node, up_child.get(), branch_var, 1, std::ceil(branch_var_val));
+
+    assert(parent_vstatus.size() == original_lp.num_cols);
+    parent_node->add_children(std::move(down_child),
+                              std::move(up_child));  // child pointers moved into the tree
+  }
+
+  void graphviz_node(mip_node_t<i_t, f_t>* node_ptr, std::string label, f_t val)
```
Comment (rg20) [inline cpp/src/dual_simplex/mip_node.hpp]:
```suggestion
  void graphviz_node(mip_node_t<i_t, f_t> const* node_ptr, std::string label, f_t val)
```

File: cpp/src/dual_simplex/mip_node.hpp [hunk 12]
```diff
@@ -230,11 +242,102 @@ void remove_fathomed_nodes(std::vector<mip_node_t<i_t, f_t>*>& stack)
...
+  {
+    if (write_graphviz) {
+      log.printf("Node%d [label=\"%s %.16e\"]\n", node_ptr->node_id, label.c_str(), val);
+    }
+  }
+
+  void graphviz_edge(mip_node_t<i_t, f_t>* origin_ptr,
```
Comment (rg20) [inline cpp/src/dual_simplex/mip_node.hpp]:
```suggestion
  void graphviz_edge(mip_node_t<i_t, f_t> const* origin_ptr,
```

File: cpp/src/dual_simplex/mip_node.hpp [hunk 13]
```diff
@@ -230,11 +242,102 @@ void remove_fathomed_nodes(std::vector<mip_node_t<i_t, f_t>*>& stack)
...
+                     mip_node_t<i_t, f_t>* dest_ptr,
```
Comment (rg20) [inline cpp/src/dual_simplex/mip_node.hpp]:
```suggestion
                     mip_node_t<i_t, f_t> const* dest_ptr,
```

File: cpp/src/dual_simplex/simplex_solver_settings.hpp (hunk 4 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/simplex_solver_settings.hpp]: I will experiment a bit with the different configurations

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 1 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp]: Good idea! I will implement this class.

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 14]
```diff
@@ -260,12 +224,50 @@ f_t branch_and_bound_t<i_t, f_t>::get_upper_bound()
...
+#pragma omp atomic read
+    lb          = lower_bounds_[i];
+    lower_bound = std::min(lb, lower_bound);
+  }
+
   return lower_bound;
 }
 
+template <typename i_t, typename f_t>
+mip_status_t branch_and_bound_t<i_t, f_t>::get_status()
```
Comment (rg20) [inline cpp/src/dual_simplex/branch_and_bound.cpp]:
```suggestion
mip_status_t branch_and_bound_t<i_t, f_t>::get_status() const
```

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 15]
```diff
@@ -260,12 +224,50 @@ f_t branch_and_bound_t<i_t, f_t>::get_upper_bound()
...
+  mip_status_t status;
+
+#pragma omp atomic read
+  status = status_;
+
+  return status;
+}
+
+template <typename i_t, typename f_t>
+i_t branch_and_bound_t<i_t, f_t>::get_heap_size()
```
Comment (rg20) [inline cpp/src/dual_simplex/branch_and_bound.cpp:251]:
```suggestion
i_t branch_and_bound_t<i_t, f_t>::get_heap_size() const
```

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 16]
```diff
@@ -260,12 +224,50 @@ f_t branch_and_bound_t<i_t, f_t>::get_upper_bound()
...
+{
+  mutex_heap_.lock();
+  i_t size = heap_.size();
+  mutex_heap_.unlock();
+  return size;
+}
+
+template <typename i_t, typename f_t>
+i_t branch_and_bound_t<i_t, f_t>::get_active_subtrees()
```
Comment (rg20) [inline cpp/src/dual_simplex/branch_and_bound.cpp]:
```suggestion
i_t branch_and_bound_t<i_t, f_t>::get_active_subtrees() const
```

File: cpp/src/dual_simplex/mip_node.hpp (hunk 10 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/mip_node.hpp]: Although its is possible to move everything to `std::thread`, some parts of the code will be quite inefficient without a thread pool or other type of thread management. `std::atomic` for floating-point variables is not available until C++20 (and some features will only appear in C++26, e.g., `fetch_max`). While openmp offers everything ready out-of-the-box and its quite popular in the HPC world.

For instance, in the previous implementation of strong branching with `std::thread` there was quite a lot of unbalanced distribution of load across the threads, such that some threads spent idling a large portion of time. After switching to `openmp`, I can use the built-in dynamic scheduling to balance the load across the threads and improve efficiency.

Comment (nguidotti) [reply cpp/src/dual_simplex/mip_node.hpp]: But I agree that we should adopt a single parallel model across the entire codebase.

File: cpp/src/dual_simplex/branch_and_bound.hpp (hunk 6 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.hpp]: `FINISHED` here means that the branch-and-bound ended naturally, i.e., it run out of nodes to explore. It can lead to `optimal/unbounded/infeasible` after checking the final bounds.

Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.hpp]: I am open to suggestion for other names. Maybe `FINISHED_EXPLORATION`.

File: cpp/src/dual_simplex/mip_node.hpp (hunk 7 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/mip_node.hpp:209]: Mostly yes. It sets `parent = nullptr`, `node_id = 0` and `depth = 0` so it is disconnected to the main tree (that is why is called `detach_copy`). I will add a comment to be more clear.

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 15 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp:251]: In this case, it cannot be `const` due to the mutex.

File: cpp/src/dual_simplex/branch_and_bound.hpp (hunk 6 above)
Comment (rg20) [reply cpp/src/dual_simplex/branch_and_bound.hpp]: So this is an intermediate state before you determine the true status right? 

you could consider COMPLETED

**Comment by nguidotti** [comment]
@aliceb-nv @akifcorduk @chris-maes  
With this PR, branch-and-bound benefits with a larger number of threads, so I set the default `num_threads` to `omp_get_max_threads() / n_gpus` in the `run_MIP` file. Besides setting the flags  `--num-cpu-threads` and `--n_gpus`, the number of threads can also be controlled via `OMP_NUM_THREADS`.

File: cpp/src/mip/diversity/recombiners/sub_mip.cuh (hunk 5 above)
Comment (nguidotti) [reply cpp/src/mip/diversity/recombiners/sub_mip.cuh]: For now, I set to 1 best first thread and 1 diving thread. Later, we can experiment in allocating more threads to submip. @akifcorduk

File: cpp/src/dual_simplex/branch_and_bound.hpp [hunk 17]
```diff
@@ -18,40 +18,75 @@
...
-  NODE_LIMIT = 4,
-  NUMERICAL  = 5,
-  UNSET      = 6
+  OPTIMAL    = 0,  // The optimal integer solution was found
+  UNBOUNDED  = 1,  // The problem is unbounded
+  INFEASIBLE = 2,  // The problem is infeasible
+  TIME_LIMIT = 3,  // The solver reached a time limit
+  NODE_LIMIT = 4,  // The maximum number of nodes was reached (not implemented)
+  NUMERICAL  = 5,  // The solver encountered a numerical error
+  RUNNING    = 6,  // The solver is currently exploring the tree
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.hpp]: I'm not sure I understand why the `RUNNING` status is needed. `mip_status_t` is meant to be a status code returned after the solver has completed running. I'm also a little worried about `COMPLETED`. Ideally when the solver is finished it has a well-defined status: like optimal, unbounded, etc. COMPLETED doesn't give much info.

File: cpp/src/dual_simplex/branch_and_bound.hpp [hunk 18]
```diff
@@ -135,10 +154,24 @@ class branch_and_bound_t {
 
   // Pseudocosts
   pseudo_costs_t<i_t, f_t> pc_;
-  std::mutex mutex_pc_;
+  omp_mutex_t mutex_pc_;
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.hpp]: Nit: Should the pseudcosts maintain their own mutex?

File: cpp/src/dual_simplex/branch_and_bound.hpp [hunk 19]
```diff
@@ -150,24 +183,38 @@ class branch_and_bound_t {
...
-  // Explore the search tree using the depth-first search strategy.
-  mip_status_t dive(i_t branch_var, mip_solution_t<i_t, f_t>& solution);
-
-  // Branch the current node, creating two children.
-  void branch(mip_node_t<i_t, f_t>* parent_node,
-              i_t branch_var,
-              f_t branch_var_val,
-              const std::vector<variable_status_t>& parent_vstatus);
+  // Ramp-up phase of the solver, where we greedily expand the tree until
+  // a certain depth is reached. This is done recursively using OpenMP tasks.
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.hpp]: Nit: Is this depth comment out of date?

File: cpp/src/dual_simplex/branch_and_bound.hpp [hunk 20]
```diff
@@ -150,24 +183,38 @@ class branch_and_bound_t {
...
+                           csc_matrix_t<i_t, f_t>& Arow,
+                           i_t initial_heap_size);
+
+  // Explore the search tree using the best-first search with plunging strategy.
+  void explore_subtree(search_tree_t<i_t, f_t>& search_tree,
+                       mip_node_t<i_t, f_t>* start_node,
+                       lp_problem_t<i_t, f_t>& leaf_problem,
+                       csc_matrix_t<i_t, f_t>& Arow);
+
+  // Each "main" thread pop a node from the global heap and then perform a plunge
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.hpp]: Nit: pop -> pops

Comment (chris-maes) [reply cpp/src/dual_simplex/branch_and_bound.hpp]: Nit: perform -> performs

File: cpp/src/dual_simplex/branch_and_bound.hpp [hunk 21]
```diff
@@ -150,24 +183,38 @@ class branch_and_bound_t {
...
+  // (i.e., a shallow dive) into the subtree determined by the node.
+  void best_first_thread(search_tree_t<i_t, f_t>& search_tree,
+                         lp_problem_t<i_t, f_t>& leaf_problem,
+                         csc_matrix_t<i_t, f_t>& Arow);
+
+  // Each diving thread pop the first node from the dive queue and then perform
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.hpp]: Nit: pop -> pops, perform -> performs

File: cpp/src/dual_simplex/branch_and_bound.hpp [hunk 22]
```diff
@@ -150,24 +183,38 @@ class branch_and_bound_t {
...
+  // a deep dive into the subtree determined by the node.
+  void diving_thread(lp_problem_t<i_t, f_t>& leaf_problem, csc_matrix_t<i_t, f_t>& Arow);
 
   // Solve the LP relaxation of a leaf node.
-  mip_status_t solve_node_lp(mip_node_t<i_t, f_t>* node_ptr,
-                             lp_problem_t<i_t, f_t>& leaf_problem,
-                             csc_matrix_t<i_t, f_t>& Arow,
-                             const std::vector<variable_type_t>& var_types,
-                             f_t upper_bound);
+  node_status_t solve_node_lp(search_tree_t<i_t, f_t>& search_tree,
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.hpp]: Nit: it's a bit strange that a function called `solve_node_lp` takes in the upper bound. We might consider calling this something different to take into the account that it is also updating and the tree. Maybe
`solve_node_lp_and_update_tree`

File: cpp/src/dual_simplex/mip_node.hpp [hunk 23]
```diff
@@ -230,11 +246,97 @@ void remove_fathomed_nodes(std::vector<mip_node_t<i_t, f_t>*>& stack)
...
+    : root(root_lower_bound, basis), num_nodes(0), log(log)
+  {
+  }
+
+  search_tree_t(mip_node_t<i_t, f_t>&& node, logger_t& log)
+    : root(std::move(node)), num_nodes(0), log(log)
+  {
+  }
+
+  f_t get_lower_bound() const { return root.lower_bound; }
```
Comment (chris-maes) [inline cpp/src/dual_simplex/mip_node.hpp]: Is this correct? Shouldn't the lower bound of the tree depend on the nodes other than the root?

File: cpp/src/dual_simplex/mip_node.hpp [hunk 24]
```diff
@@ -230,11 +246,97 @@ void remove_fathomed_nodes(std::vector<mip_node_t<i_t, f_t>*>& stack)
...
+                 branch_var,
+                 branch_dir == 0 ? "<=" : ">=",
+                 bound);
+    }
+  }
+
+  mip_node_t<i_t, f_t> root;
+  omp_mutex_t mutex;
+  omp_atomic_t<i_t> num_nodes;
+  logger_t log;
```
Comment (chris-maes) [inline cpp/src/dual_simplex/mip_node.hpp]: Why is the tree storing the logger?

File: cpp/src/dual_simplex/pseudo_costs.cpp [hunk 25]
```diff
@@ -79,7 +79,7 @@ void strong_branch_helper(i_t thread_id,
                                           solution,
                                           iter,
                                           child_edge_norms);
-      const f_t lp_solve_time                = toc(lp_start_time);
+      // const f_t lp_solve_time                = toc(lp_start_time);
```
Comment (chris-maes) [inline cpp/src/dual_simplex/pseudo_costs.cpp]: Why is this commented out? Delete or uncomment this line?

File: cpp/src/dual_simplex/simplex_solver_settings.hpp [hunk 26]
```diff
@@ -59,9 +59,9 @@ struct simplex_solver_settings_t {
       refactor_frequency(100),
       iteration_log_frequency(1000),
       first_iteration_log(2),
-      num_threads(std::thread::hardware_concurrency() > 8
-                    ? (std::thread::hardware_concurrency() / 8)
-                    : std::thread::hardware_concurrency()),
+      num_threads(omp_get_max_threads() - 1),
+      num_bfs_threads(std::min(num_threads / 4, 1)),
+      num_diving_threads(std::min(num_threads - num_bfs_threads, 1)),
```
Comment (chris-maes) [inline cpp/src/dual_simplex/simplex_solver_settings.hpp:64]: Nit: what if num_threads = 1. This will create two threads.

File: cpp/src/mip/diversity/recombiners/sub_mip.cuh [hunk 27]
```diff
@@ -111,8 +111,11 @@ class sub_mip_recombiner_t : public recombiner_t<i_t, f_t> {
       branch_and_bound_settings.print_presolve_stats = false;
       branch_and_bound_settings.absolute_mip_gap_tol = context.settings.tolerances.absolute_mip_gap;
       branch_and_bound_settings.relative_mip_gap_tol = context.settings.tolerances.relative_mip_gap;
-      branch_and_bound_settings.integer_tol = context.settings.tolerances.integrality_tolerance;
-      branch_and_bound_settings.solution_callback = [this](std::vector<f_t>& solution,
+      branch_and_bound_settings.integer_tol     = context.settings.tolerances.integrality_tolerance;
+      branch_and_bound_settings.num_threads     = 2;
```
Comment (chris-maes) [inline cpp/src/mip/diversity/recombiners/sub_mip.cuh:115]: Are we sure we want to use 2 threads per sub-mip? Why not just 1 diving thread?

File: cpp/src/mip/solver.cu [hunk 28]
```diff
@@ -172,11 +172,19 @@ solution_t<i_t, f_t> mip_solver_t<i_t, f_t>::run_solver()
...
+    if (context.settings.num_cpu_threads < 0) {
+      branch_and_bound_settings.num_threads = omp_get_max_threads() - 1;
+    } else {
       branch_and_bound_settings.num_threads = std::max(1, context.settings.num_cpu_threads);
     }
     CUOPT_LOG_INFO("Using %d CPU threads for B&B", branch_and_bound_settings.num_threads);
 
+    i_t num_threads                              = branch_and_bound_settings.num_threads;
+    i_t num_bfs_threads                          = std::max(1, num_threads / 4);
+    i_t num_diving_threads                       = std::max(1, num_threads - num_bfs_threads);
```
Comment (chris-maes) [inline cpp/src/mip/solver.cu:184]: Nit: If the user set the num threads to 1, which is probably a pretty common setting, this creates two threads. I think you should handle this case by only having 1 BFS thread.

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 29]
```diff
@@ -304,16 +294,13 @@ void branch_and_bound_t<i_t, f_t>::set_new_solution(const std::vector<f_t>& solu
   mutex_upper_.unlock();
 
   if (is_feasible) {
-    mutex_branching_.lock();
-    bool currently_branching = currently_branching_;
-    mutex_branching_.unlock();
-    if (currently_branching) {
+    if (status_ == mip_status_t::RUNNING) {
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.cpp]: It seems better to keep the currently_branching variable, rather than mix up the status code by including a RUNNING term

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 30]
```diff
@@ -304,16 +294,13 @@ void branch_and_bound_t<i_t, f_t>::set_new_solution(const std::vector<f_t>& solu
...
       f_t user_obj    = compute_user_objective(original_lp_, obj);
       f_t user_lower  = compute_user_objective(original_lp_, get_lower_bound());
       std::string gap = user_mip_gap<f_t>(user_obj, user_lower);
 
       settings_.log.printf(
-        "H                        %+13.6e  %+10.6e                      %s %9.2f\n",
+        "H                           %+13.6e    %+10.6e                        %s %9.2f\n",
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.cpp:303]: Why did the spaces change here? Spacing is critical to keep the columns in the logs.

Comment (chris-maes) [reply cpp/src/dual_simplex/branch_and_bound.cpp:303]: If the space changes here they need to change everywhere. Is the change intentional?

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 31]
```diff
@@ -424,6 +411,7 @@ void branch_and_bound_t<i_t, f_t>::repair_heuristic_solutions()
           f_t obj              = compute_user_objective(original_lp_, repaired_obj);
           f_t lower            = compute_user_objective(original_lp_, get_lower_bound());
           std::string user_gap = user_mip_gap<f_t>(obj, lower);
+
           settings_.log.printf(
             "H                        %+13.6e  %+10.6e                      %s %9.2f\n",
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.cpp:416]: Does the spacing need to change here?

File: cpp/src/dual_simplex/branch_and_bound.cpp
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.cpp]: Nit: Maybe this should be called `solve_node_with_dual_simplex`

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 32]
```diff
@@ -567,36 +583,34 @@ dual::status_t branch_and_bound_t<i_t, f_t>::node_dual_simplex(
...
+                                                          mip_node_t<i_t, f_t>* node_ptr,
+                                                          lp_problem_t<i_t, f_t>& leaf_problem,
+                                                          csc_matrix_t<i_t, f_t>& Arow,
+                                                          f_t upper_bound,
+                                                          logger_t& log,
+                                                          char symbol)
 {
-  logger_t log;
-  log.log                                      = false;
+  logger_t pc_log;
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.cpp]: Why create another logger here and why call it `pc_log`? If it's for the psuedocosts, maybe move it's creation to right before it is used.

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 33]
```diff
@@ -567,36 +583,34 @@ dual::status_t branch_and_bound_t<i_t, f_t>::node_dual_simplex(
...
 }
 
 template <typename i_t, typename f_t>
-mip_status_t branch_and_bound_t<i_t, f_t>::solve_node_lp(
-  mip_node_t<i_t, f_t>* node_ptr,
-  lp_problem_t<i_t, f_t>& leaf_problem,
-  csc_matrix_t<i_t, f_t>& Arow,
-  const std::vector<variable_type_t>& var_types,
-  f_t upper_bound)
+node_status_t branch_and_bound_t<i_t, f_t>::solve_node_lp(search_tree_t<i_t, f_t>& search_tree,
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.cpp]: Nit: solve_node_lp_and_update_tree

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 32 above)
Comment (chris-maes) [reply cpp/src/dual_simplex/branch_and_bound.cpp]: Also, if the whole point of the pc_log is to just turn logging off you can pass in the same logger that you pass into dual simplex.

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 34]
```diff
@@ -609,262 +623,390 @@ mip_status_t branch_and_bound_t<i_t, f_t>::solve_node_lp(
...
+    search_tree->graphviz_node(node, "cutoff", node->lower_bound);
+    search_tree->update_tree(node, node_status_t::FATHOMED);
+    return;
+  }
+
+  f_t now = toc(stats_.start_time);
+
+  if (omp_get_thread_num() == 0) {
+    if (nodes_explored % 1000 == 0 || abs_gap < 10 * settings_.absolute_mip_gap_tol ||
+        nodes_explored < 1000) {
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.cpp]: We probably don't want to print every node for the first 1000 nodes. Consider removing the `nodes_explored < 1000` condition here. We should probably also maintain the time since the last log and not log too frequently.

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 35]
```diff
@@ -609,262 +623,390 @@ mip_status_t branch_and_bound_t<i_t, f_t>::solve_node_lp(
...
-                           now);
-      last_log = tic();
+
+    f_t now = toc(stats_.start_time);
+
+    if (tid == 0) {
+      f_t time_since_log = last_log == 0 ? 1.0 : toc(last_log);
+
+      if (((nodes_since_last_log % 1000 == 0 || abs_gap < 10 * settings_.absolute_mip_gap_tol ||
+            nodes_since_last_log < 1000) &&
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.cpp]: Won't the clause `nodes_since_last_log` make you log every node. Don't you want to only log if the `nodes_since_last_log >= 1000` or the time since last log >= 1?

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 36]
```diff
@@ -609,262 +623,390 @@ mip_status_t branch_and_bound_t<i_t, f_t>::solve_node_lp(
...
-                           node_ptr->depth,
-                           nodes_explored > 0 ? stats_.total_lp_iters / nodes_explored : 0,
-                           user_gap.c_str(),
-                           now);
-      last_log = tic();
+
+    f_t now = toc(stats_.start_time);
+
+    if (tid == 0) {
+      f_t time_since_log = last_log == 0 ? 1.0 : toc(last_log);
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.cpp]: Nit: time_since_log -> time_since_last_log

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 37]
```diff
@@ -609,262 +623,390 @@ mip_status_t branch_and_bound_t<i_t, f_t>::solve_node_lp(
...
     if (toc(stats_.start_time) > settings_.time_limit) {
-      settings_.log.printf("Hit time limit. Stopping\n");
-      status = mip_status_t::TIME_LIMIT;
+      status_ = mip_status_t::TIME_LIMIT;
       break;
     }
 
-    status = solve_node_lp(node_ptr, leaf_problem, Arow, var_types_, upper_bound);
+    // We are just checking for numerical issues or timeout during the LP solve, otherwise
+    // lp_status is set to RUNNING.
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.cpp]: I'm not sure I understand this comment.

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 38]
```diff
@@ -609,262 +623,390 @@ mip_status_t branch_and_bound_t<i_t, f_t>::solve_node_lp(
...
 
-    if (node_ptr->status == node_status_t::HAS_CHILDREN) {
-      // the heap does not own the unique_ptr the tree does
-      heap.push(node_ptr->get_down_child());
-      heap.push(node_ptr->get_up_child());
-    }
-  }
+    } else if (node_status == node_status_t::HAS_CHILDREN) {
+      if (stack.size() > 0) {
+        mip_node_t<i_t, f_t>* node = stack.back();
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.cpp:856]: Please add a comment here. Something like:

// The stack should only contain the children of the current parent. If the stack size is greater than 0,
// we pop the current node from the stack and place it in the global heap, since we are about to 
// add the two children to the stack

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 39]
```diff
@@ -973,81 +1119,66 @@ mip_status_t branch_and_bound_t<i_t, f_t>::solve(mip_solution_t<i_t, f_t>& solut
...
+    &search_tree.root, branch_var, root_relax_soln_.x[branch_var], root_vstatus_, original_lp_);
+  stats_.nodes_unexplored = 2;
 
+  settings_.log.printf("Exploring the B&B tree using %d threads (%d diving threads)\n",
+                       settings_.num_threads,
+                       settings_.num_diving_threads);
   settings_.log.printf(
-    "| Explored | Unexplored | Objective   |    Bound    | Depth | Iter/Node |  Gap   | "
-    "   Time \n");
+    " | Explored | Unexplored |    Objective    |     Bound     | Depth | Iter/Node |   Gap    "
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.cpp:1145]: Please make sure all log lines are updated with the extra spacing.

File: cpp/src/dual_simplex/branch_and_bound.hpp (hunk 17 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.hpp]: Previously, there was an extra variable called `currently_branching`, which was used by the heuristics to insert new feasible solutions. It was merged with the `mip_status_t`.
- `RUNNING` indicates that the B&B is being executed and new feasible solutions can be inserted.
- `COMPLETED` is needed for terminating the diving threads as it indicates that the best-first threads have terminated and the entire tree has been explored. Note that `COMPLETED` is only temporary and will be replaced by `OPTIMAL` or `INFEASIBLE` shortly after. `COMPLETED` can only replace `RUNNING`, but not other status.

File: cpp/src/dual_simplex/mip_node.hpp (hunk 23 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/mip_node.hpp]: This is only used in the end when we need to retrieve the lower bound from the root node. This method is actually not needed since the root is public, so I will remove it.

File: cpp/src/dual_simplex/branch_and_bound.hpp (hunk 17 above)
Comment (chris-maes) [reply cpp/src/dual_simplex/branch_and_bound.hpp]: Let's undo the merging of these two concepts. I think it leads to issue. I'd prefer if they were separate.

File: cpp/src/dual_simplex/mip_node.hpp (hunk 24 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/mip_node.hpp]: Mostly for the `graphviz` routines in the tree to be self-contained. But I can change to pass the logger as a parameter.

File: cpp/src/mip/diversity/recombiners/sub_mip.cuh (hunk 27 above)
Comment (nguidotti) [reply cpp/src/mip/diversity/recombiners/sub_mip.cuh:115]: The code does not work with just diving threads. It must have at least 1 BFS thread for exploring the tree.

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 30 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp:303]: With the parallel code, some columns started to overflow into others, so I had to increase the spacing between them. I did make sure that all the entries are aligned. 
(just an observation: this will be much easier to do if we had access to `std::format` from C++20).

File: cpp/src/dual_simplex/branch_and_bound.hpp (hunk 17 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.hpp]: In any case, I will bring back the `currently_branching` variable.

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 34 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp]: Well, the ramp-up phase is often quite short (the tree typically has less than 100 at the end) and the thread `0` will is reponsible for only a handful of nodes. I will re-add the `last_log` variable.

File: cpp/src/dual_simplex/branch_and_bound.hpp (hunk 18 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.hpp]: Done

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 37 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp]: This was leftover of a previous commit.

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 40]
```diff
@@ -260,12 +235,27 @@ f_t branch_and_bound_t<i_t, f_t>::get_upper_bound()
 template <typename i_t, typename f_t>
 f_t branch_and_bound_t<i_t, f_t>::get_lower_bound()
 {
-  mutex_lower_.lock();
-  const f_t lower_bound = lower_bound_;
-  mutex_lower_.unlock();
+  f_t lower_bound = inf;
+  mutex_heap_.lock();
+  if (heap_.size() > 0) { lower_bound = heap_.top()->lower_bound; }
```
Comment (akifcorduk) [inline cpp/src/dual_simplex/branch_and_bound.cpp]: What if the heap is empty?

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 41]
```diff
@@ -515,29 +528,57 @@ void branch_and_bound_t<i_t, f_t>::add_feasible_solution(f_t leaf_objective,
...
   mutex_upper_.unlock();
+}
+
+template <typename i_t, typename f_t>
+std::pair<mip_node_t<i_t, f_t>*, mip_node_t<i_t, f_t>*>
+branch_and_bound_t<i_t, f_t>::child_selection(mip_node_t<i_t, f_t>* node_ptr)
+{
+  const i_t branch_var     = node_ptr->get_down_child()->branch_var;
+  const f_t branch_var_val = node_ptr->get_down_child()->fractional_val;
+  const f_t down_val       = std::floor(root_relax_soln_.x[branch_var]);
```
Comment (akifcorduk) [inline cpp/src/dual_simplex/branch_and_bound.cpp:539]: Adding a very small epsilon for numerical issue might be helpful here.

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 42]
```diff
@@ -515,29 +528,57 @@ void branch_and_bound_t<i_t, f_t>::add_feasible_solution(f_t leaf_objective,
...
-  lp_solution_t<i_t, f_t>& leaf_solution,
-  std::vector<bool>& bounds_changed,
   csc_matrix_t<i_t, f_t>& Arow,
   f_t upper_bound,
-  logger_t& log)
+  logger_t& log,
+  char symbol)
 {
-  i_t node_iter = 0;
+  f_t abs_fathom_tol = settings_.absolute_mip_gap_tol / 10;
```
Comment (akifcorduk) [inline cpp/src/dual_simplex/branch_and_bound.cpp:562]: Is /10 an arbitrary choice?

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 43]
```diff
@@ -562,309 +603,396 @@ dual::status_t branch_and_bound_t<i_t, f_t>::node_dual_simplex(
...
-    if (upper_bound < node_ptr->lower_bound) {
-      // This node was put on the heap earlier but its lower bound is now greater than the current
-      // upper bound
-      update_tree(node_ptr, node_status_t::FATHOMED);
-      graphviz_node(settings_, node_ptr, "cutoff", node_ptr->lower_bound);
+    f_t abs_gap     = upper_bound - lower_bound;
+    f_t rel_gap     = user_relative_gap(original_lp_, upper_bound, lower_bound);
+
+    // This is based on three assumptions:
+    // - The stack only contains sibling nodes, i.e., the current node and its siblings, if it
```
Comment (akifcorduk) [inline cpp/src/dual_simplex/branch_and_bound.cpp]: You use plural siblings, but there is only 1 sibling right?

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 44]
```diff
@@ -562,309 +603,396 @@ dual::status_t branch_and_bound_t<i_t, f_t>::node_dual_simplex(
...
+    // exists
+    // - The current node and its siblings uses the lower bound of the parent before solving the LP
+    // relaxation
+    // - The lower bound of the parent is lower or equal to its children
+    local_lower_bounds_[id] = lower_bound;
```
Comment (akifcorduk) [inline cpp/src/dual_simplex/branch_and_bound.cpp:802]: I am not sure if this is 100% correct. You use `local_lower_bounds_` to compute the global lower bound later in the main thread. However, the lower_bound in the this thread (stack exploration) is the node's lower bound not the whole sub-tree's. So when you backtrack to previous nodes in the tree, the lower bound will go down because the next node you are going to process inherits the lower bound from its parent. Does that make sense ?

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 45]
```diff
@@ -562,309 +603,396 @@ dual::status_t branch_and_bound_t<i_t, f_t>::node_dual_simplex(
...
+    if (heap_.size() > 0) {
+      node_ptr = heap_.top();
+      heap_.pop();
+      active_subtrees_++;
+    }
+    mutex_heap_.unlock();
+
+    if (node_ptr != nullptr) {
+      if (get_upper_bound() < node_ptr->lower_bound) {
+        // This node was put on the heap earlier but its lower bound is now greater than the
```
Comment (akifcorduk) [inline cpp/src/dual_simplex/branch_and_bound.cpp:912]: Does this happen often? If so, why don't we rebalance the heap when a new incumbent is found?

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 46]
```diff
@@ -562,309 +603,396 @@ dual::status_t branch_and_bound_t<i_t, f_t>::node_dual_simplex(
...
+         rel_gap > settings_.relative_mip_gap_tol &&
+         (active_subtrees_ > 0 || get_heap_size() > 0)) {
+    mip_node_t<i_t, f_t>* node_ptr = nullptr;
+
+    // If there any node left in the heap, we pop the top node and explore it.
+    mutex_heap_.lock();
+    if (heap_.size() > 0) {
+      node_ptr = heap_.top();
+      heap_.pop();
+      active_subtrees_++;
```
Comment (akifcorduk) [inline cpp/src/dual_simplex/branch_and_bound.cpp:906]: What is the point of keeping track of active_subtrees? We always increment 1 and decrement 1 within the same loop iteration.

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 47]
```diff
@@ -562,309 +603,396 @@ dual::status_t branch_and_bound_t<i_t, f_t>::node_dual_simplex(
...
+    std::optional<mip_node_t<i_t, f_t>> start_node;
 
-  mip_node_t<i_t, f_t> root_node(root_objective_, root_vstatus_);
-  graphviz_node(settings_, &root_node, "lower bound", root_objective_);
+    mutex_dive_queue_.lock();
+    if (dive_queue_.size() > 0) { start_node = dive_queue_.pop(); }
+    mutex_dive_queue_.unlock();
 
-  branch(&root_node, branch_var, root_relax_soln_.x[branch_var], root_vstatus_);
+    if (start_node) {
```
Comment (akifcorduk) [inline cpp/src/dual_simplex/branch_and_bound.cpp]: nitpick, `.has_value` would be more readable.

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 48]
```diff
@@ -562,309 +603,396 @@ dual::status_t branch_and_bound_t<i_t, f_t>::node_dual_simplex(
...
-  lp_problem_t leaf_problem = original_lp_;
+      while (stack.size() > 0 && status_ == mip_exploration_status_t::RUNNING) {
+        mip_node_t<i_t, f_t>* node_ptr = stack.front();
+        stack.pop_front();
+        f_t upper_bound = get_upper_bound();
+        f_t rel_gap     = user_relative_gap(original_lp_, upper_bound, node_ptr->lower_bound);
 
-  csc_matrix_t<i_t, f_t> Arow(1, 1, 1);
-  original_lp_.A.transpose(Arow);
+        if (node_ptr->lower_bound > upper_bound || rel_gap > settings_.relative_mip_gap_tol) {
```
Comment (akifcorduk) [inline cpp/src/dual_simplex/branch_and_bound.cpp]: I am not sure if i get why `rel_gap > settings_.relative_mip_gap_tol` is needed. It will almost always hold right?

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 49]
```diff
@@ -562,309 +603,396 @@ dual::status_t branch_and_bound_t<i_t, f_t>::node_dual_simplex(
...
-      const f_t down_dist      = branch_var_val - down_val;
-      const f_t up_dist        = up_val - branch_var_val;
-
-      if (down_dist < up_dist) {
-        node_stack.push_back(node_ptr->get_up_child());
-        node_stack.push_back(node_ptr->get_down_child());
-      } else {
-        node_stack.push_back(node_ptr->get_down_child());
-        node_stack.push_back(node_ptr->get_up_child());
+          if (dive_queue_.size() < 4 * settings_.num_diving_threads) {
```
Comment (akifcorduk) [inline cpp/src/dual_simplex/branch_and_bound.cpp]: Could you put 4 in a named variable?

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 50]
```diff
@@ -973,81 +1104,74 @@ mip_status_t branch_and_bound_t<i_t, f_t>::solve(mip_solution_t<i_t, f_t>& solut
...
-  mutex_branching_.lock();
-  currently_branching_ = true;
-  mutex_branching_.unlock();
+  status_ = mip_exploration_status_t::RUNNING;
 
-  std::future<mip_status_t> diving_thread;
+#pragma omp parallel num_threads(settings_.num_threads)
+  {
+    // Make a copy of the original LP. We will modify its bounds at each leaf
+    lp_problem_t leaf_problem = original_lp_;
```
Comment (akifcorduk) [inline cpp/src/dual_simplex/branch_and_bound.cpp:1163]: Instead of copying the whole problem, do you think we could only copy the bounds ? For large problems this might cause memory limit issues.

File: cpp/src/dual_simplex/mip_node.hpp [hunk 51]
```diff
@@ -230,11 +246,96 @@ void remove_fathomed_nodes(std::vector<mip_node_t<i_t, f_t>*>& stack)
...
+              const f_t branch_var_val,
+              const std::vector<variable_status_t>& parent_vstatus,
+              const lp_problem_t<i_t, f_t>& original_lp,
+              logger_t& log)
+  {
+    i_t id = num_nodes.fetch_add(2);
+
+    // down child
+    auto down_child = std::make_unique<mip_node_t<i_t, f_t>>(
+      original_lp, parent_node, ++id, branch_var, 0, branch_var_val, parent_vstatus);
```
Comment (akifcorduk) [inline cpp/src/dual_simplex/mip_node.hpp]: `branch_var_val` is not rounded on both children, is that on purpose?

File: cpp/src/mip/diversity/recombiners/sub_mip.cuh (hunk 27 above)
Comment (akifcorduk) [reply cpp/src/mip/diversity/recombiners/sub_mip.cuh:115]: I think we slowly need to care about thread pools and total amount of threads used at a time.

File: cpp/src/mip/solver.cu [hunk 52]
```diff
@@ -172,11 +172,19 @@ solution_t<i_t, f_t> mip_solver_t<i_t, f_t>::run_solver()
...
-    if (context.settings.num_cpu_threads != -1) {
+    if (context.settings.num_cpu_threads < 0) {
+      branch_and_bound_settings.num_threads = omp_get_max_threads() - 1;
+    } else {
       branch_and_bound_settings.num_threads = std::max(1, context.settings.num_cpu_threads);
     }
     CUOPT_LOG_INFO("Using %d CPU threads for B&B", branch_and_bound_settings.num_threads);
 
+    i_t num_threads                              = branch_and_bound_settings.num_threads;
+    i_t num_bfs_threads                          = std::max(1, num_threads / 4);
```
Comment (akifcorduk) [inline cpp/src/mip/solver.cu:183]: When do we need more bfs threads? Does it even work now? How do we update the heap and global lower bound?

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 40 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp]: The global lower bound is calculated in two parts.
- Let `l0` denote the lower bound from the heap. If the heap is empty, then `l0 = inf`. Otherwise, `l0` is equal to the lower bound of the top of the heap. 
- Let `lk` denote the local lower bound of the parent of the current node being processed by the thread `k`.
The global lower bound is `min {l0, l1, ..., lk}`. Here, `lk` is equal to the root objective in the beginning of the algorithm.

Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp]: So, if the heap is empty, then we only consider the local lower bounds of the threads. If there is no active thread, then we calculate the lower bound from the root of the B&B tree (similar than before).

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 42 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp:562]: Originally, it was hardcoded to be `1E-5` (and the default tolerance was set to `1E-4`). In this way, the solver can adjust based on the user-specified tolerance. It was divided by `10` to be more restricted, but other values are possible.

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 43 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp]: Yes, I will update the comment.

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 44 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp:802]: The stack only contains siblings nodes and the lower bound stored in each node is equal to its parent before solving the LP. Note that we do not update the lower bound afterwards in the iteration.

Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp:802]: Therefore, if we backtrack to the sibling, it will have the same lower bound since it shares the same parent.

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 46 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp:906]: If the heap is empty, but there are still active threads, then they may insert new nodes to the heap and the solver cannot terminate. `active_subtrees_` is used to track the number of active threads.

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 48 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp]: No, in most MIPLIB instances, the optimality is proven in terms of the relative gap (if the solver can explore the entire tree). Imagine that you have objective `obj = 1.002E6` , a lower bound  `lb = 1.001E6` and a tolerance `eps = 1E-2`, then `gap = 1000`, but the relative gap is `1E-3`, which is below the tolerance.

File: cpp/src/dual_simplex/mip_node.hpp (hunk 51 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/mip_node.hpp]: The original code also does not round the variables as the corresponding variable stores the fractional value. I will renamed to `fractional_value` to be more clear.

File: cpp/src/mip/solver.cu (hunk 52 above)
Comment (nguidotti) [reply cpp/src/mip/solver.cu:183]: Yes, the code works with an arbitrary number of bfs and diving threads. Each additional threads helps the code to explore the tree faster, such that the lower bound improves faster and there is more interesting nodes to perform dives from.

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 50 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp:1163]: True, but this will require us to change the call to the dual_phase2 method. I will create a follow-up issue after this PR is merged.

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 45 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp:912]: This only occurs at the end of the solver, when the solver has already explored most of the tree. Since we are using `std::priority_queue`, the solver does not have access to the underlying container, so rebalancing is not possible at the moment.

Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp:912]: We need to implement the heap ourselves (or better yet, adapt the `diving_queue_t` class to be more general).

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 40 above)
Comment (akifcorduk) [reply cpp/src/dual_simplex/branch_and_bound.cpp]: Let's say BFS explored the tree and at some point the heap is empty. BFS should have a generated a global lower bound up to that point. So we would be missing a valid lower bound in our global lower bound computation.

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 44 above)
Comment (akifcorduk) [reply cpp/src/dual_simplex/branch_and_bound.cpp:802]: If we are not updating lower bound during the iterations, what is the point of keeping it? It will always be the same as the root of the subtree right?

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 42 above)
Comment (chris-maes) [reply cpp/src/dual_simplex/branch_and_bound.cpp:562]: It's possible for dual simplex to be a bit off in it's objective. Since it introduces perturbations to the objective and currently doesn't remove them. We don't want to accidentally fathom a node due to this error in the objective. So we need some tolerance here. The exact value for the tolerance can be debated. But this seems reasonable for now.

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 44 above)
Comment (chris-maes) [reply cpp/src/dual_simplex/branch_and_bound.cpp:802]: I agree its a bit strange. The lower bound will be incorrect during the ramp up phase. This is probably not too bad, considering the ramp up phase is short-lived. We should correct it at some point.

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 45 above)
Comment (chris-maes) [reply cpp/src/dual_simplex/branch_and_bound.cpp:912]: I think this can occur before the end of the solve. We don't remove nodes from the heap when we find a new incumbent. That would be costly. Instead we check when we pop the node off the heap if they still need to be solved. 

I agree we should implement our own heap. But still not sure it would be worth traversing the heap each time a new incumbent is found.

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 50 above)
Comment (chris-maes) [reply cpp/src/dual_simplex/branch_and_bound.cpp:1163]: Yes, we could have a special version of dual simplex that took in bound separately. It would save some memory. But I think the memory associated with storing an extra copy of the problem for each thread is small compared to the memory required for storing a basis factorization of each thread. So I would say this is lower priority.

File: cpp/src/mip/solver.cu (hunk 52 above)
Comment (chris-maes) [reply cpp/src/mip/solver.cu:183]: @nguidotti did you do a benchmark comparing the MIP gap (difference between our upper and lower bound--- as opposed to the optimality gap which is the difference between our upper bound and the optimal objective) to see if adding the extra BFS threads improved it?

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 30 above)
Comment (chris-maes) [reply cpp/src/dual_simplex/branch_and_bound.cpp:303]: It's pretty easy do now :)

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 31 above)
Comment (chris-maes) [reply cpp/src/dual_simplex/branch_and_bound.cpp:416]: Why didn't the spacing change here?  If you had to make changes other places?

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 53]
```diff
@@ -445,35 +433,62 @@ void branch_and_bound_t<i_t, f_t>::repair_heuristic_solutions()
...
 {
-  // down child
-  auto down_child = std::make_unique<mip_node_t<i_t, f_t>>(
-    original_lp_, parent_node, ++stats_.num_nodes, branch_var, 0, branch_var_val, parent_vstatus);
+  mip_status_t mip_status = mip_status_t::UNSET;
 
-  graphviz_edge(
-    settings_, parent_node, down_child.get(), branch_var, 0, std::floor(branch_var_val));
+  if (status_ == mip_exploration_status_t::NUMERICAL) {
+    settings_.log.printf("Numerical issue encountered. Stopping the solver...\n");
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.cpp:442]: When do we stop the solver if we run into numerical issue? It would be ok to continue the solve if a dive ran into numerical issue. The only case where we need to stop the solve is if the node at the top of the heap runs into numerical issues.

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 54]
```diff
@@ -562,309 +603,391 @@ dual::status_t branch_and_bound_t<i_t, f_t>::node_dual_simplex(
...
+                           node->depth,
+                           nodes_explored > 0 ? stats_.total_lp_iters / nodes_explored : 0,
+                           gap_user.c_str(),
+                           now);
 
-  // Make a copy of the original LP. We will modify its bounds at each leaf
-  lp_problem_t leaf_problem = original_lp_;
-  csc_matrix_t<i_t, f_t> Arow(1, 1, 1);
-  original_lp_.A.transpose(Arow);
+      stats_.nodes_since_last_log = 0;
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.cpp:737]: Do you also need to set `stats_.last_log = tic()`?

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 55]
```diff
@@ -562,309 +603,391 @@ dual::status_t branch_and_bound_t<i_t, f_t>::node_dual_simplex(
...
+    solve_node(*search_tree, node, leaf_problem, Arow, upper_bound, settings_.log, 'B');
+
+  if (node_status == node_status_t::TIME_LIMIT) {
+    status_ = mip_exploration_status_t::TIME_LIMIT;
+    return;
+
+  } else if (node_status == node_status_t::HAS_CHILDREN) {
+    stats_.nodes_unexplored += 2;
+
+    if (stats_.nodes_unexplored < initial_heap_size) {
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.cpp:756]: A comment here would be helpful. Maybe something like:

// If we haven't generated enough nodes to keep the threads busy, continue the ramp up phase

During the ramp up phase, when you aren't pushing the nodes in the heap, are the nodes only tracked via the search tree?

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 56]
```diff
@@ -562,309 +603,391 @@ dual::status_t branch_and_bound_t<i_t, f_t>::node_dual_simplex(
...
+#pragma omp task
+      exploration_ramp_up(
+        search_tree, node->get_down_child(), leaf_problem, Arow, initial_heap_size);
+
+#pragma omp task
+      exploration_ramp_up(search_tree, node->get_up_child(), leaf_problem, Arow, initial_heap_size);
+
+    } else {
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.cpp:764]: A comment here would be helpful. Maybe something like:

// We've generated enough nodes, push further nodes onto the heap

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 57]
```diff
@@ -562,309 +603,391 @@ dual::status_t branch_and_bound_t<i_t, f_t>::node_dual_simplex(
...
+  std::deque<mip_node_t<i_t, f_t>*> stack;
+  stack.push_front(start_node);
 
-  f_t user_upper_bound = compute_user_objective(original_lp_, get_upper_bound());
-  f_t user_lower_bound = compute_user_objective(original_lp_, lower_bound);
-  f_t rel_gap          = relative_gap(user_upper_bound, user_lower_bound);
-  while (gap > settings_.absolute_mip_gap_tol && rel_gap > settings_.relative_mip_gap_tol &&
-         heap.size() > 0) {
+  while (stack.size() > 0 && status_ == mip_exploration_status_t::RUNNING) {
     repair_heuristic_solutions();
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.cpp]: Is this being run by all threads? If so, do all threads need to try to repair heuristic solutions? Couldn't we restrict it so only a single thread, say thread 0, tried to repair?

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 58]
```diff
@@ -562,309 +603,391 @@ dual::status_t branch_and_bound_t<i_t, f_t>::node_dual_simplex(
...
-                           user_gap.c_str(),
-                           now);
-      last_log = tic();
+
+    f_t now = toc(stats_.start_time);
+
+    if (id == 0) {
+      f_t time_since_last_log = stats_.last_log == 0 ? 1.0 : toc(stats_.last_log);
+
+      if (((stats_.nodes_since_last_log >= 1000 || abs_gap < 10 * settings_.absolute_mip_gap_tol) &&
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.cpp:818]: Why 1000 nodes since last log here? But 100 nodes since last log above?

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 59]
```diff
@@ -562,309 +603,391 @@ dual::status_t branch_and_bound_t<i_t, f_t>::node_dual_simplex(
...
+        continue;
+      }
 
-  if (stats_.nodes_unexplored == 0) {
-    mutex_lower_.lock();
-    lower_bound = lower_bound_ = root_node.lower_bound;
-    mutex_lower_.unlock();
+      // Best-first search with plunging
+      explore_subtree(id, search_tree, node_ptr, leaf_problem, Arow);
+      active_subtrees_--;
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.cpp:922]: I'm not sure I understand what `active_subtrees` is tracking. And why you decrement it here. Could you explain?

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 60]
```diff
@@ -562,309 +603,391 @@ dual::status_t branch_and_bound_t<i_t, f_t>::node_dual_simplex(
...
-        node_stack.push_back(node_ptr->get_down_child());
-      } else {
-        node_stack.push_back(node_ptr->get_down_child());
-        node_stack.push_back(node_ptr->get_up_child());
+        } else if (node_status == node_status_t::HAS_CHILDREN) {
+          auto [first, second] = child_selection(node_ptr);
+          stack.push_front(second);
+          stack.push_front(first);
+
+          if (dive_queue_.size() < min_diving_queue_size_) {
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.cpp:989]: It would be good to have a comment here about why you are adding to the dive_queue

Comment (chris-maes) [reply cpp/src/dual_simplex/branch_and_bound.cpp:989]: Is this the only place we add to the dive queue? I thought the BFS threads would also add to the dive queue

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 61]
```diff
@@ -973,81 +1099,80 @@ mip_status_t branch_and_bound_t<i_t, f_t>::solve(mip_solution_t<i_t, f_t>& solut
...
+  search_tree_t<i_t, f_t> search_tree(root_objective_, root_vstatus_);
+  search_tree.graphviz_node(settings_.log, &search_tree.root, "lower bound", root_objective_);
+  search_tree.branch(&search_tree.root,
+                     branch_var,
+                     root_relax_soln_.x[branch_var],
+                     root_vstatus_,
+                     original_lp_,
+                     log);
+
+  settings_.log.printf("Exploring the B&B tree using %d threads (%d diving threads)\n",
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.cpp]: Nit: do you also want to print the number of BFS threads?

File: cpp/src/dual_simplex/branch_and_bound.hpp [hunk 62]
```diff
@@ -18,40 +18,82 @@
...
+  OPTIMAL    = 0,  // The optimal integer solution was found
+  UNBOUNDED  = 1,  // The problem is unbounded
+  INFEASIBLE = 2,  // The problem is infeasible
+  TIME_LIMIT = 3,  // The solver reached a time limit
+  NODE_LIMIT = 4,  // The maximum number of nodes was reached (not implemented)
+  NUMERICAL  = 5,  // The solver encountered a numerical error
+  UNSET      = 6,  // The status is not set
+};
+
+enum class mip_exploration_status_t {
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.hpp:46]: Thanks for splitting this apart. I'm still a little confused why you need the status TIME_LIMIT, NODE_LIMIT, and NUMERICAL here. Why can't this status just be RUNNING or COMPLETED?

File: cpp/src/dual_simplex/mip_node.hpp [hunk 63]
```diff
@@ -30,11 +30,12 @@ namespace cuopt::linear_programming::dual_simplex {
...
-  INTEGER_FEASIBLE = 2,  // Node has an integer feasible solution
-  INFEASIBLE       = 3,  // Node is infeasible
-  FATHOMED         = 4,  // Node objective is greater than the upper bound
-  HAS_CHILDREN     = 5,  // Node has children to explore
+  INTEGER_FEASIBLE = 1,  // Node has an integer feasible solution
+  INFEASIBLE       = 2,  // Node is infeasible
+  FATHOMED         = 3,  // Node objective is greater than the upper bound
+  HAS_CHILDREN     = 4,  // Node has children to explore
+  NUMERICAL        = 5,  // Encountered numerical issue when solving the LP relaxation
+  TIME_LIMIT       = 6   // Time out during the LP relaxation
```
Comment (chris-maes) [inline cpp/src/dual_simplex/mip_node.hpp:38]: Why is TIME_LIMIT needed here?

File: cpp/src/dual_simplex/pseudo_costs.cpp [hunk 64]
```diff
@@ -79,7 +79,6 @@ void strong_branch_helper(i_t thread_id,
                                           solution,
                                           iter,
                                           child_edge_norms);
-      const f_t lp_solve_time                = toc(lp_start_time);
```
Comment (chris-maes) [inline cpp/src/dual_simplex/pseudo_costs.cpp:82]: Why is this removed?

File: cpp/src/mip/diversity/recombiners/sub_mip.cuh (hunk 27 above)
Comment (chris-maes) [reply cpp/src/mip/diversity/recombiners/sub_mip.cuh:115]: OK. It doesn't need to be addressed in this PR. But it would be good to understand why we can't just do a dive in a sub-MIP and why we need a BFS thread.

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 40 above)
Comment (chris-maes) [reply cpp/src/dual_simplex/branch_and_bound.cpp]: That valid lower bound generated by BFS would be stored in the tree. And would be accounted for later when the size of the heap is zero.

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 55 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp:756]: Yes, they only exist in the tree.

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 57 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp]: Done

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 40 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp]: In this case, we get the lower bounds from the threads. But there is a catch here that I did not consider. At the very end, not all threads will be active, so the lower bounds may be incorrect. I will fix this by updating the local lower bounds to `inf` when the thread exits the loop.

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 44 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp:802]: I will create a follow-up issue so we can keep track of this.

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 59 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp:922]: If the heap is empty, but there are still active threads, then they may insert new nodes to the heap and the solver cannot terminate. active_subtrees_ is used to track the number of active threads.

File: cpp/src/dual_simplex/branch_and_bound.hpp (hunk 62 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.hpp:46]: The solver checks the (internal) status to determines when to stop (basically, when it is not `RUNNING`). The other status is to keep track of why we stopped the solver (it will be translated later to the `mip_status_t`).

File: cpp/src/dual_simplex/pseudo_costs.cpp (hunk 64 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/pseudo_costs.cpp:82]: This variable was not used in the code below.

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 60 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp:989]: The BFS also adds to the diving queue. It is around the line `856`  in the `explore_subtree` routine.

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 59 above)
Comment (chris-maes) [reply cpp/src/dual_simplex/branch_and_bound.cpp:922]: That's helpful. Thanks for the explaination.

File: cpp/src/mip/local_search/rounding/constraint_prop.cu [hunk 65]
```diff
@@ -907,7 +907,6 @@ bool constraint_prop_t<i_t, f_t>::find_integer(
 
   CUOPT_LOG_DEBUG("Bounds propagation rounding: unset vars %lu", unset_integer_vars.size());
   if (unset_integer_vars.size() == 0) {
-    CUOPT_LOG_ERROR("No integer variables provided in the bounds prop rounding");
```
Comment (chris-maes) [inline cpp/src/mip/local_search/rounding/constraint_prop.cu]: Maybe these should be DEBUG?

File: cpp/src/mip/local_search/rounding/lb_constraint_prop.cu [hunk 66]
```diff
@@ -770,7 +770,6 @@ bool lb_constraint_prop_t<i_t, f_t>::find_integer(
 {
   RAFT_CHECK_CUDA(problem.handle_ptr->get_stream());
   if (orig_sol.problem_ptr->n_integer_vars == 0) {
-    CUOPT_LOG_ERROR("No integer variables provided in the bounds prop rounding");
```
Comment (chris-maes) [inline cpp/src/mip/local_search/rounding/lb_constraint_prop.cu:773]: Maybe these should be DEBUG?

File: cpp/src/dual_simplex/branch_and_bound.cpp [hunk 67]
```diff
@@ -669,10 +669,14 @@ node_status_t branch_and_bound_t<i_t, f_t>::solve_node(search_tree_t<i_t, f_t>&
 
   } else {
     search_tree.graphviz_node(log, node_ptr, "numerical", 0.0);
-    log.printf("Encountered LP status %d on node %d. This indicates a numerical issue.\n",
+    lower_bound_ceiling_.fetch_min(node_ptr->lower_bound);
+    log.printf("LP returned status %d on node %d. This indicates a numerical issue.\n",
                lp_status,
                node_ptr->node_id);
+    log.printf("The maximum lower bound is set to %+10.6e.\n",
```
Comment (chris-maes) [inline cpp/src/dual_simplex/branch_and_bound.cpp]: We should be a bit careful with this message. Remember we also solve maximization problems. So from the user's perspective this could be an upper bound. 

I think it's not a bad idea to issue this message as a warning. But I would say:

"The best bound is set to ..."

Or "The bound is set to ..."

Comment (chris-maes) [reply cpp/src/dual_simplex/branch_and_bound.cpp]: Do the diving threads use this code?

Comment (chris-maes) [reply cpp/src/dual_simplex/branch_and_bound.cpp]: That is would you issue this message if a diving thread encountered a node with numerical issues?

File: cpp/src/dual_simplex/branch_and_bound.hpp (hunk 62 above)
Comment (chris-maes) [reply cpp/src/dual_simplex/branch_and_bound.hpp:46]: But if we hit a TIME_LIMIT or NODE_LIMIT shouldn't any part of the code be able to tell that just by checking the time and the number of nodes? 

I think there is probably an opportunity to simplify the code a bit here and not mix the return status with whether branch and bound is running or not.

File: cpp/src/dual_simplex/branch_and_bound.cpp (hunk 67 above)
Comment (nguidotti) [reply cpp/src/dual_simplex/branch_and_bound.cpp]: The logger is disabled for diving threads. They will only mark the node as having numerical issues and then move on.

Only the BFS threads will issue the warning. With that said, the code should probably check if it is in the BFS thread or not before updating the variable. I will update the code now.
